"""The one unauthenticated route that is not a provider webhook.

Everything here exists because the caller is a stranger. The tenant comes from
a form key looked up in `channel_routes` — never from the request claiming an
organization — and the org is bound before the first write, exactly like the
webhook handlers do it. Under default-deny RLS a missed binding writes nothing,
which is the failure mode we want: a lost submission is recoverable, a
submission filed into another agency's dashboard is not.
"""
from __future__ import annotations

import json
import logging
import re
import time
from collections import deque
from datetime import UTC, date, datetime
from typing import Any, Literal

import httpx
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import FileResponse, Response, StreamingResponse
from pydantic import BaseModel, Field, field_validator
from sqlalchemy import func, select, update
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.db.base import get_db
from app.models.channel_route import CHANNEL_WEB
from app.models.landing import LANDING_EVENT_TYPES, LandingSession
from app.services.capture import (
    MAX_CONSENT_TEXT,
    MAX_MESSAGE,
    MAX_NAME,
    CaptureRejected,
    FormSubmission,
    capture_lead,
    clean_attribution,
    validate_submission,
)
from app.services.landing_analytics import (
    browser_of,
    clip,
    device_of,
    fold_events,
    geo_of,
    in_app_of,
    merge_values,
    new_events,
    os_of,
    referrer_host_of,
    source_of,
)
from app.services.lead_notify import send_new_lead_notice
from app.services.media_public import parse_range, read_range, resolve_public_media
from app.services.tenant_context import set_org_id
from app.services.tenant_resolver import WebhookOrgUnresolved, webhook_org_or_refuse

log = logging.getLogger(__name__)
router = APIRouter()

TURNSTILE_VERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify"

# What a landing session key looks like: 32 hex characters, generated by the
# page. Enforced by the beacon's schema (a malformed one there is a client bug
# and there is nothing to lose by refusing it) and merely *checked* on the
# capture path, where refusing would cost a lead.
_SESSION_KEY = re.compile(r"[0-9a-f]{32}")

# ── Rate limiting ────────────────────────────────────────────────────────
# Two windows, and the second is the one that matters. A per-IP limit alone is
# decorative behind a proxy: the client IP is read from a header, and anyone
# willing to rotate that header has an unlimited per-IP budget. The global
# ceiling is what bounds the damage regardless of how many identities the
# caller invents.
#
# In-process counters are correct here only because the app is pinned to a
# single uvicorn worker — the same constraint main.py documents for the three
# background loops. Under `--workers N` these become N independent budgets and
# belong in Redis alongside those loops.
PER_IP_LIMIT = 5
PER_IP_WINDOW = 600.0
GLOBAL_LIMIT = 60
GLOBAL_WINDOW = 600.0
# Bounded so a flood of distinct (or forged) addresses cannot grow the map
# without limit — the memory itself would otherwise be the attack.
MAX_TRACKED_IPS = 5_000

_hits: dict[str, deque[float]] = {}
_global_hits: deque[float] = deque()

# The landing beacons get their OWN budget, and that is the whole point of
# these four constants existing beside the four above rather than reusing them.
# One ordinary visit sends a page view, a section view, a scroll depth and
# maybe a tap — four attempts against a per-address budget of five. Sharing the
# counters would mean a visitor who reads the page attentively can no longer
# submit the form, which is precisely backwards.
#
# The numbers are high because the work is small (one upsert and a few inserts,
# no captcha call, no outbound mail) and low enough that a script cannot fill
# the table from one address unattended.
EVENTS_PER_IP_LIMIT = 60
EVENTS_PER_IP_WINDOW = 600.0
EVENTS_GLOBAL_LIMIT = 3_000
EVENTS_GLOBAL_WINDOW = 600.0
# 16 KB: a full batch of 25 events, each with its metadata, plus the attribution
# and the referrer, fits with room to spare — and it is sixteen times tighter
# than the 256 KB every other route gets by default.
EVENTS_MAX_BODY = 16_384
EVENTS_MAX_PER_BATCH = 25

_ev_hits: dict[str, deque[float]] = {}
_ev_global_hits: deque[float] = deque()

# A beacon endpoint that logs per request is an amplifier: the cheapest way to
# fill an operator's disk would be to send it rubbish. These remember the last
# day each condition was reported, so a flood produces one line, not a million.
_global_warned: dict[object, date] = {}
_reject_warned: dict[object, date] = {}
_cap_warned: dict[object, date] = {}


def _warn_once(seen: dict[object, date], key: object, message: str) -> None:
    today = datetime.now(UTC).date()
    if seen.get(key) == today:
        return
    seen[key] = today
    log.warning("%s", message)


def _path_only(path: str | None) -> str | None:
    """The path with any query string removed.

    The tracker sends `location.pathname`, but a client is a client: if one
    ever sends `pathname + search`, a URL carrying an email address in a
    parameter would land verbatim in a column, against the promise that nothing
    identifying is stored. Cut here, where it cannot be forgotten.
    """
    cleaned = clip(path)
    if cleaned is None:
        return None
    return cleaned.split("?", 1)[0].split("#", 1)[0] or "/"


def _prune(window: deque[float], now: float, span: float) -> None:
    while window and now - window[0] > span:
        window.popleft()


def _charge_ip(
    store: dict[str, deque[float]], ip: str, limit: int, span: float, now: float | None
) -> bool:
    """Charge one address against a bounded per-address budget."""
    stamp = time.monotonic() if now is None else now
    window = store.get(ip)
    if window is None:
        if len(store) >= MAX_TRACKED_IPS:
            # Drop the coldest tracked address rather than refuse service.
            coldest = min(store, key=lambda k: store[k][-1] if store[k] else 0.0)
            store.pop(coldest, None)
        window = store[ip] = deque()
    _prune(window, stamp, span)
    if len(window) >= limit:
        return True
    window.append(stamp)
    return False


def _ip_limited(ip: str, now: float | None = None) -> bool:
    """Charge this address for a capture attempt; say whether it is over budget.

    Charged for EVERY attempt that reaches it, including honeypot hits and
    submissions the captcha will reject. The budget is per address and bounded,
    so spending it on refused work costs the caller and nobody else.
    """
    return _charge_ip(_hits, ip, PER_IP_LIMIT, PER_IP_WINDOW, now)


def _ev_ip_limited(ip: str, now: float | None = None) -> bool:
    """The same, against the beacons' own budget. See EVENTS_PER_IP_LIMIT."""
    return _charge_ip(_ev_hits, ip, EVENTS_PER_IP_LIMIT, EVENTS_PER_IP_WINDOW, now)


def _global_limited(now: float | None = None) -> bool:
    """Charge the platform-wide budget, and say whether it is exhausted.

    Deliberately charged LAST — after the honeypot, after the per-IP budget and
    after the captcha. It used to be charged first, which made it a kill switch
    anyone could hold down: sixty tokenless posts from sixty forged addresses
    were each refused with 400 and each still consumed a slot, so the captcha
    that is supposed to be the defence a script cannot outspend was bypassed
    for availability, and every agency on the install lost lead capture for ten
    minutes. Now a request only spends this budget once it has proven it is
    worth writing.
    """
    stamp = time.monotonic() if now is None else now
    _prune(_global_hits, stamp, GLOBAL_WINDOW)
    if len(_global_hits) >= GLOBAL_LIMIT:
        return True
    _global_hits.append(stamp)
    return False


def _ev_global_limited(now: float | None = None) -> bool:
    """Charge the platform-wide beacon budget. Separate from capture's, so a
    flood of beacons can never be what stops a lead from being written."""
    stamp = time.monotonic() if now is None else now
    _prune(_ev_global_hits, stamp, EVENTS_GLOBAL_WINDOW)
    if len(_ev_global_hits) >= EVENTS_GLOBAL_LIMIT:
        return True
    _ev_global_hits.append(stamp)
    return False


def reset_rate_limits() -> None:
    """Test seam. Nothing in the app calls this."""
    _hits.clear()
    _global_hits.clear()
    _ev_hits.clear()
    _ev_global_hits.clear()


def client_ip(request: Request) -> str:
    """The visitor's address, as well as it can be known.

    `CF-Connecting-IP` first: Cloudflare overwrites it on every request, so a
    client cannot forge it through the tunnel this install actually runs behind.
    `X-Forwarded-For` is next and is only as trustworthy as whatever set it —
    hence the global ceiling above, which does not depend on any of this being
    honest.
    """
    return _client_ip_parts(request)[0]


def _client_ip_parts(request: Request) -> tuple[str, bool]:
    """(address, came_from_a_proxy_header).

    The flag matters for Turnstile. When neither header is present the socket
    peer is NOT the visitor: the POST is proxied by the Next.js server through
    its `/api/*` rewrite, so `request.client.host` is the frontend container's
    address on the Docker bridge. Sending that to Cloudflare as `remoteip` is a
    classic source of spurious verification failures — the field is optional,
    and omitting it is better than asserting something false.
    """
    cf = (request.headers.get("cf-connecting-ip") or "").strip()
    if cf:
        return cf[:45], True
    forwarded = (request.headers.get("x-forwarded-for") or "").split(",")[0].strip()
    if forwarded:
        return forwarded[:45], True
    return (request.client.host if request.client else "unknown")[:45], False


async def _turnstile_ok(token: str | None, ip: str | None) -> bool:
    """Verify a Turnstile token, or pass when no secret is configured.

    Configured-but-unreachable fails CLOSED. A captcha that waves everyone
    through whenever Cloudflare has a bad minute is not a captcha, and this is
    the only defence here that a determined script cannot simply outspend.
    """
    secret = (get_settings().TURNSTILE_SECRET or "").strip()
    if not secret:
        return True
    if not token:
        return False
    payload = {"secret": secret, "response": token}
    if ip:
        payload["remoteip"] = ip
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.post(TURNSTILE_VERIFY_URL, data=payload)
            return bool(response.json().get("success"))
    except Exception as exc:  # noqa: BLE001
        log.error("Turnstile verification failed to complete: %s", exc)
        return False


class PublicLeadIn(BaseModel):
    # The public key of the form, as configured in channel_routes. Optional:
    # a single-agency install has nothing to disambiguate, and requiring a key
    # there would mean every customer must run a platform API call before their
    # own contact form works.
    form: str | None = Field(default=None, max_length=254)
    name: str | None = Field(default=None, max_length=MAX_NAME)
    email: str | None = Field(default=None, max_length=254)
    phone: str | None = Field(default=None, max_length=40)
    message: str | None = Field(default=None, max_length=MAX_MESSAGE)
    consent: bool = False
    consent_text: str | None = Field(default=None, max_length=MAX_CONSENT_TEXT)
    utm: dict[str, str] | None = None
    # The landing page's own visit key, when the tracker is running. Its only
    # job is to join this submission to the session that produced it, which is
    # what turns "we got a lead" into "the visit that became this lead came
    # from TikTok, read three sections and tapped call first".
    #
    # A separate field rather than an attribution key on purpose: the whitelist
    # in `capture.py` is pinned by a test that reads it, by an assert on its
    # size and by the public form's documentation, and it means "which campaign
    # produced this lead" — a per-visit identifier is not that, and it must
    # never reach `lead.meta`.
    #
    # Deliberately NOT pinned to the session-key shape here, unlike the beacon's
    # own field. A `pattern` on this model rejects the whole submission with
    # 422, so a bug in the tracker's key generator would stop costing an
    # analytics row and start costing the LEAD — the exact inversion the link
    # below is written to avoid. Bounded only, and checked for shape at the
    # point of use, where a bad value is simply not looked up.
    session_id: str | None = Field(default=None, max_length=64)
    turnstile_token: str | None = Field(default=None, max_length=4_000)
    # Honeypot. Named for something a browser autofill would plausibly target
    # and hidden in the markup, so a human never sees it and a bot fills it in.
    website: str | None = Field(default=None, max_length=200)

    # No trimming validator here, deliberately, and it took writing one to find
    # out why: `services/capture.py` already normalises every field that is
    # stored — `clean_text` for name and message (which trims AND collapses
    # runs of whitespace), `normalize_email` and `normalize_phone` for the
    # other two. A validator on this model changed nothing that reached the
    # database; measured on identical POSTs, the stored row was byte-identical
    # with and without it. Code that does nothing is worse than absent: it
    # reads as coverage.
    #
    # Two fields must never acquire one, which is the part worth writing down:
    #
    # - `website` is the honeypot, tested below as `if body.website` — before
    #   the captcha and before tenant resolution. A whitespace-only value is
    #   truthy, so a bot filling the hidden field with spaces is caught today.
    #   Trimming it to None would wave that bot straight through.
    # - `consent_text` reaches `clean_text` like the rest, so it is already
    #   collapsed rather than stored verbatim. Worth knowing before anyone
    #   relies on it reading back exactly as the person saw it.


@router.post("/leads", status_code=202)
async def capture(
    body: PublicLeadIn, request: Request, db: AsyncSession = Depends(get_db)
) -> dict[str, bool]:
    ip, ip_is_from_a_proxy_header = _client_ip_parts(request)

    # ── Order matters, and each step is placed for a reason ──────────────
    # 1. Per-IP budget first, charged even for the honeypot. It used to sit
    #    AFTER the honeypot branch, so `{"website": "bot"}` was an unmetered
    #    endpoint: two hundred consecutive posts all answered 202 and left
    #    every counter untouched.
    if _ip_limited(ip):
        log.warning("Rate limit refused a capture from %s", ip)
        raise HTTPException(status_code=429, detail="too_many_requests")

    if body.website:
        # Answer exactly like a good submission. Telling a bot it was detected
        # is free tuning feedback for whoever wrote it.
        log.info("Honeypot tripped from %s", ip)
        return {"ok": True}

    # 2. Shape of the submission, BEFORE the tenant is resolved. A probe with
    #    no email and no phone used to return 422 for a live form key and 404
    #    for a dead one, which made this a quiet enumeration oracle: unlike a
    #    202 probe it writes no lead, so a scan left no trace anywhere the
    #    operator looks. Same answer now regardless of the key.
    submission = FormSubmission(
        name=body.name,
        email=body.email,
        phone=body.phone,
        message=body.message,
        consent=body.consent,
        consent_text=body.consent_text,
        attribution=body.utm or {},
        ip=ip,
        user_agent=request.headers.get("user-agent"),
    )
    try:
        validate_submission(submission)
    except CaptureRejected as exc:
        raise HTTPException(status_code=422, detail=exc.code) from exc

    # A lead we cannot reach is not a lead. Every field on this form is optional,
    # which was correct while there were two automatic channels; SMS is not one
    # of them today (Twilio accepts and the carrier drops it — error 30034,
    # measured), so a phone-only submission produces a row nobody can answer.
    # Refusing it in front of the person, while they are still on the page and
    # can add an address, is better than accepting it and going quiet.
    #
    # After the captcha check would be wrong: this costs nothing to evaluate and
    # tells an honest visitor what to fix, whereas a bot never gets this far.
    if get_settings().CAPTURE_REQUIRE_EMAIL and not (submission.email or "").strip():
        raise HTTPException(status_code=422, detail="email_required")

    # 3. Captcha before the global budget is touched. A request the captcha
    #    will refuse must not be able to spend a slot: that turned the ceiling
    #    into a kill switch anyone could hold down without solving anything.
    if not await _turnstile_ok(
        body.turnstile_token, ip if ip_is_from_a_proxy_header else None
    ):
        raise HTTPException(status_code=400, detail="captcha_failed")

    # 4. The platform-wide budget, charged BEFORE the tenant lookup rather than
    #    after it. Resolving a form key is a database round trip, and with the
    #    charge at the end a caller rotating the IP header could drive an
    #    unbounded number of them: the per-IP budget resets with every forged
    #    address, so nothing counted the work. Charging here means the ceiling
    #    bounds real work, not just successful writes.
    if _global_limited():
        log.error(
            "Global capture ceiling reached — lead capture is refused for "
            "every agency until the window clears. If this is not a flood, "
            "raise GLOBAL_LIMIT; if it is, configure TURNSTILE_SECRET."
        )
        raise HTTPException(status_code=429, detail="too_many_requests")

    try:
        org_id = await webhook_org_or_refuse(
            CHANNEL_WEB,
            body.form,
            # A key that was supplied must match a route. Without this, an
            # agency offboarded the ordinary way — suspend, delete routes —
            # leaves a live landing page whose submissions get filed into
            # whichever agency remains.
            fallback_when_unmapped=not body.form,
        )
    except WebhookOrgUnresolved as exc:
        # 404, not 503. The form key is public — it ships in the landing page —
        # but the set of valid keys is not, and a distinguishable error turns
        # this endpoint into an oracle for enumerating an operator's tenants.
        log.error("refusing web capture — %s", exc)
        raise HTTPException(status_code=404, detail="unknown_form") from exc

    set_org_id(org_id)

    try:
        captured = await capture_lead(submission, db)
    except CaptureRejected as exc:
        await db.rollback()
        raise HTTPException(status_code=422, detail=exc.code) from exc
    except Exception:
        await db.rollback()
        log.exception("Web capture failed")
        raise HTTPException(status_code=500, detail="capture_failed") from None

    await db.commit()

    # After the commit, on purpose: the lead must be durable before anyone is
    # told about it, and a notification failure must cost the notification,
    # never the capture. Duplicates are already filtered — a double-submit
    # returns status "duplicate" above and must not email the agency twice.
    if captured.get("status") == "ok":
        await send_new_lead_notice(captured["lead_id"], captured.get("message_id"))
    # Join the visit to the lead it produced. Wrapped, and after everything
    # else, because this is analytics: the lead is already durable and already
    # notified, and a failure here must cost a row in a report, never a 500
    # that sends the visitor round the submit button a second time.
    if (
        _SESSION_KEY.fullmatch(body.session_id or "")
        and captured.get("lead_id")
        and get_settings().LANDING_EVENTS_ENABLED
    ):
        try:
            await db.execute(
                update(LandingSession)
                .where(
                    LandingSession.org_id == org_id,
                    LandingSession.session_key == body.session_id,
                    LandingSession.lead_id.is_(None),
                )
                .values(lead_id=captured["lead_id"], form_submitted_at=datetime.now(UTC))
            )
            await db.commit()
        except Exception as exc:  # noqa: BLE001
            log.warning("Could not link landing session to lead: %s", exc)
            try:
                await db.rollback()
            except Exception:  # noqa: BLE001
                # The rollback is a courtesy — the lead is already durable and
                # the session is about to be discarded either way. Letting this
                # escape would turn an analytics failure into a 500 on a
                # submission that already succeeded, which is the one outcome
                # this whole block exists to prevent.
                log.warning("Rollback after the link failure also failed")

    # Deliberately says nothing about whether the lead was new, merged or
    # duplicate: that is a membership oracle for anyone who wants to test
    # whether an address is in an agency's book.
    return {"ok": True}


# ── Landing analytics ────────────────────────────────────────────────────


class LandingEventIn(BaseModel, extra="forbid"):
    t: str = Field(max_length=40)
    meta: dict[str, Any] | None = None

    @field_validator("t")
    @classmethod
    def _known(cls, v: str) -> str:
        if v not in LANDING_EVENT_TYPES:
            raise ValueError("unknown event type")
        return v

    @field_validator("meta")
    @classmethod
    def _small(cls, v: dict[str, Any] | None) -> dict[str, Any] | None:
        """Bounded in both directions: at most five keys, and values that are
        short strings or plain numbers. The metadata is a label — which section,
        which percentage, which button — and anything larger arriving here is
        somebody using a public endpoint as free storage."""
        if v is None:
            return None
        if len(v) > 5:
            raise ValueError("too many metadata keys")
        out: dict[str, Any] = {}
        for key, value in v.items():
            if not isinstance(key, str) or len(key) > 40:
                raise ValueError("bad metadata key")
            if isinstance(value, bool) or value is None:
                continue
            if isinstance(value, int):
                out[key] = value
            elif isinstance(value, str):
                trimmed = value.strip()[:120]
                if trimmed:
                    out[key] = trimmed
            else:
                raise ValueError("bad metadata value")
        return out


class LandingBatchIn(BaseModel, extra="forbid"):
    form: str | None = Field(default=None, max_length=254)
    # Random, client-side, and it dies with the tab. Pinned to a shape so a row
    # key can never be an arbitrary string somebody chose.
    session: str = Field(pattern=r"^[0-9a-f]{32}$")
    path: str | None = Field(default=None, max_length=200)
    lang: Literal["en", "es"] | None = None
    screen_w: int | None = Field(default=None, ge=0, le=10_000)
    utm: dict[str, str] | None = None
    referrer: str | None = Field(default=None, max_length=500)
    events: list[LandingEventIn] = Field(min_length=1, max_length=EVENTS_MAX_PER_BATCH)


@router.post("/landing")
async def landing_events(request: Request, db: AsyncSession = Depends(get_db)) -> Response:
    """What a visitor did on the marketing page, before there was a lead.

    Unauthenticated and uncaptcha'd, because it is sent by a page anyone can
    open and by `navigator.sendBeacon`, which cannot solve a challenge and
    cannot wait for one. Three things stand in for the captcha, and the third
    is the one that actually bounds the table: its own rate budget, a 16 KB
    body of at most 25 events with a closed set of names, and a **per-agency
    daily cap on new sessions**. Without that cap the rate limit bounds the
    speed of writing permanent rows and nothing bounds their number.

    Always 204, even when it declines to do anything. The sender has nothing
    useful to do with the distinction, and a public endpoint that answers
    differently for a valid and an invalid form key is an oracle for
    enumerating an operator's tenants. Honest caveat, since a comment that
    overclaims is worse than none: the STATUS is identical, but a resolvable
    key does more work than an unresolvable one, so the two are distinguishable
    by timing to anyone willing to average enough samples.

    The body is read and parsed by hand rather than declared as a Pydantic
    parameter because `sendBeacon` sends `text/plain` — Chromium refuses a JSON
    Blob from a beacon in some contexts — and FastAPI would answer a valid
    batch with 422 purely over the content type.
    """
    ip = client_ip(request)
    if _ev_ip_limited(ip):
        return Response(status_code=429)

    # Charged BEFORE the body is read and parsed. The sibling endpoint carries
    # a comment about the opposite order being a past outage, and the reasoning
    # inverts here: `capture` charges last so a request the captcha will refuse
    # cannot spend the platform's budget. There is no captcha on this path, so
    # a caller rotating the client-IP header would otherwise buffer 16 KB and
    # run a JSON parse per request without ever touching the ceiling.
    if _ev_global_limited():
        _warn_once(_global_warned, "landing", "Landing beacon ceiling reached")
        return Response(status_code=429)

    raw = await request.body()
    if len(raw) > EVENTS_MAX_BODY:
        return Response(status_code=413)
    try:
        payload = json.loads(raw) if raw else None
        body = LandingBatchIn.model_validate(payload)
    except Exception as exc:  # noqa: BLE001
        # 400 for both a malformed body and one that fails validation — the
        # sender is our own script and a distinguishing error helps nobody but
        # somebody probing the schema. But it is LOGGED, once per window: the
        # tracker is the only caller, so a schema drift on its side would make
        # every batch 400 and leave the table at zero with nothing anywhere
        # saying why, and `sendBeacon` has no error handler to notice.
        _warn_once(_reject_warned, "landing", f"Landing beacon rejected: {exc}")
        return Response(status_code=400)

    if not get_settings().LANDING_EVENTS_ENABLED:
        return Response(status_code=204)

    try:
        org_id = await webhook_org_or_refuse(
            CHANNEL_WEB, body.form, fallback_when_unmapped=not body.form
        )
    except WebhookOrgUnresolved as exc:
        log.info("Dropping landing beacon — %s", exc)
        return Response(status_code=204)

    # Bound BEFORE the first query on `db`: the org id is injected into the
    # transaction when it begins, so a query issued before this point runs with
    # an empty `app.current_org_id` and, under default-deny RLS, sees nothing.
    set_org_id(org_id)

    now = datetime.now(UTC)
    batch = [(e.t, e.meta or {}) for e in body.events]

    try:
        session_id = await _landing_session_id(db, org_id, body, request, now)
        if session_id is None:
            return Response(status_code=204)

        await db.execute(
            update(LandingSession)
            .where(LandingSession.id == session_id)
            .values(**merge_values(fold_events(batch), now))
        )
        db.add_all(new_events(org_id, session_id, batch, now))
        await db.commit()
    except Exception:
        await db.rollback()
        log.exception("Landing beacon failed")
        # Still 204: the page must not learn anything from a failure here, and
        # a beacon has nobody to report to.
        return Response(status_code=204)

    return Response(status_code=204)


async def _landing_session_id(
    db: AsyncSession,
    org_id: int,
    body: LandingBatchIn,
    request: Request,
    now: datetime,
) -> int | None:
    """The id of this visit's session row, creating it if this is its first
    beacon. None when the agency has already opened its quota of sessions
    today, which is the only thing bounding how many permanent rows an
    anonymous caller can create.

    The cap is on CREATION, not on beacons: a visit already recorded keeps
    merging, so a real visitor is never truncated mid-page — only a caller
    inventing session keys is stopped.
    """
    found = (
        await db.execute(
            select(LandingSession.id).where(
                LandingSession.org_id == org_id,
                LandingSession.session_key == body.session,
            )
        )
    ).scalar_one_or_none()
    if found is not None:
        return found

    if await _sessions_today(db, org_id, now) >= get_settings().LANDING_SESSIONS_PER_DAY:
        _warn_once(
            _cap_warned,
            org_id,
            f"Landing session cap reached for organization {org_id}; new visits "
            "are not being recorded until tomorrow",
        )
        return None

    attribution = clean_attribution(body.utm)
    host = referrer_host_of(body.referrer)
    ua = request.headers.get("user-agent")
    country, region, city = geo_of(request.headers)

    # Core INSERT, not the ORM: `before_flush` is what stamps `org_id` on this
    # project's tables, and it never sees a Core statement. Hence the explicit
    # value — without it the policy's WITH CHECK refuses the row.
    inserted = (
        await db.execute(
            pg_insert(LandingSession)
            .values(
                org_id=org_id,
                session_key=body.session,
                first_seen_at=now,
                last_seen_at=now,
                landing_path=_path_only(body.path),
                lang=body.lang,
                utm_source=attribution.get("utm_source"),
                utm_medium=attribution.get("utm_medium"),
                utm_campaign=attribution.get("utm_campaign"),
                utm_content=attribution.get("utm_content"),
                utm_term=attribution.get("utm_term"),
                referrer_host=host,
                source=source_of(attribution.get("utm_source"), host),
                device=device_of(ua),
                browser=browser_of(ua),
                os=os_of(ua),
                in_app=in_app_of(ua),
                country=country,
                region=region,
                city=city,
                screen_w=body.screen_w,
            )
            # First touch wins, exactly as it does for a lead's attribution: a
            # visitor who reloads with a different query string has not changed
            # where they came from. Also the race: two first beacons for one
            # visit, and the loser reads the winner's row below.
            .on_conflict_do_nothing(index_elements=["org_id", "session_key"])
            .returning(LandingSession.id)
        )
    ).scalar_one_or_none()
    if inserted is not None:
        return inserted

    return (
        await db.execute(
            select(LandingSession.id).where(
                LandingSession.org_id == org_id,
                LandingSession.session_key == body.session,
            )
        )
    ).scalar_one_or_none()


async def _sessions_today(db: AsyncSession, org_id: int, now: datetime) -> int:
    """How many visits this agency has opened since local midnight.

    Local, not UTC, because every number this feature produces is read against
    the agency's own day and a cap that resets at 5pm Denver time would be
    surprising in exactly the way an operator does not need. Counted through a
    LIMIT so the scan stops at the cap instead of walking a busy day's rows.
    """
    cap = get_settings().LANDING_SESSIONS_PER_DAY
    zone = await _agency_zone(db)
    midnight = now.astimezone(zone).replace(hour=0, minute=0, second=0, microsecond=0)
    window = (
        select(LandingSession.id)
        .where(
            LandingSession.org_id == org_id,
            LandingSession.first_seen_at >= midnight.astimezone(UTC),
        )
        .limit(cap)
        .subquery()
    )
    return (
        await db.execute(select(func.count()).select_from(window))
    ).scalar_one()


async def _agency_zone(db: AsyncSession):
    """The acting agency's timezone, or UTC if it has not set a usable one."""
    from app.models import AgentSettings
    from app.services.timezones import resolve_zone

    name = (
        await db.execute(select(AgentSettings.timezone).limit(1))
    ).scalar_one_or_none()
    return resolve_zone(name or "") or UTC


@router.api_route("/content/{piece_id}/media", methods=["GET", "HEAD"])
async def public_media(request: Request, piece_id: int):
    """The video, for the platform that is about to post it.

    Unauthenticated because Buffer has no session and cannot get one: it takes
    a URL and downloads from it when the post goes out. The gate is the piece's
    status, not the address — see `services/media_public.py` for why the signed
    link this repo would otherwise reach for cannot work here.

    Range requests are answered here rather than left to `FileResponse`, which
    in this Starlette version ignores them and returns the whole file with a
    200. Media fetchers ask for ranges, and a client that insists would see a
    broken video hours after the post was created.

    **HEAD as well as GET, and that is not tidiness.** Starlette's own `Route`
    adds HEAD to anything that answers GET; FastAPI's `APIRoute` does not, so
    `@router.get` alone returns 405 to a HEAD. Buffer asks HEAD first to see
    whether the media is really there, and on the 405 gave up with "Video could
    not be read from its URL" — a message that points at the file, the URL and
    the tunnel, none of which were the problem. Measured on the first real
    publish attempt: `HEAD /api/v1/public/content/3/media 405`.
    """
    path = await resolve_public_media(piece_id)
    if path is None:
        # The same answer for "no such piece", "not approved" and "file gone".
        raise HTTPException(status_code=404, detail="Not found")

    size = path.stat().st_size
    # Nothing in between may keep a copy: an edit revokes the piece's approval,
    # and a cached body would outlive that decision.
    headers = {"Cache-Control": "no-store", "Accept-Ranges": "bytes"}

    if request.method == "HEAD":
        # The headers a fetcher is asking for, and no body — the point of the
        # request is to learn the size and type before spending the download.
        return Response(
            status_code=200,
            media_type="video/mp4",
            headers={**headers, "Content-Length": str(size)},
        )

    try:
        span = parse_range(request.headers.get("range"), size)
    except ValueError:
        # Saying so, rather than sending bytes nobody asked for and letting the
        # client believe it got what it wanted.
        return Response(
            status_code=416, headers={**headers, "Content-Range": f"bytes */{size}"}
        )

    if span is None:
        return FileResponse(path, media_type="video/mp4", headers=headers)

    first, last = span
    return StreamingResponse(
        read_range(path, first, last),
        status_code=206,
        media_type="video/mp4",
        headers={
            **headers,
            "Content-Range": f"bytes {first}-{last}/{size}",
            "Content-Length": str(last - first + 1),
        },
    )
