"""The one unauthenticated route that is not a provider webhook.

Everything here exists because the caller is a stranger. The tenant comes from
a form key looked up in `channel_routes` — never from the request claiming an
organization — and the org is bound before the first write, exactly like the
webhook handlers do it. Under default-deny RLS a missed binding writes nothing,
which is the failure mode we want: a lost submission is recoverable, a
submission filed into another agency's dashboard is not.
"""
from __future__ import annotations

import json
import logging
import re
import time
from collections import deque
from datetime import UTC, date, datetime, timedelta
from typing import Any, Literal

import httpx
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, Response, StreamingResponse
from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator
from sqlalchemy import func, select, update
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.db.base import get_bypass_session_factory, get_db
from app.models.channel_route import CHANNEL_WEB
from app.models.landing import LANDING_EVENT_TYPES, LandingSession
from app.models.lead import Lead
from app.models.partner_brief import PartnerBrief
from app.services.brief_activity import (
    notify_finished,
    notify_opened,
    notify_progress,
    should_ping_progress,
)
from app.services.brief_notify import send_brief_answered_notice
from app.services.calculator import MAX_YEARS
from app.services.calculator_email import send_calculator_breakdown
from app.services.capture import (
    MAX_CONSENT_TEXT,
    MAX_MESSAGE,
    MAX_NAME,
    CaptureRejected,
    FormSubmission,
    capture_lead,
    clean_attribution,
    validate_submission,
)
from app.services.email_compliance import OPT_OUT_KEYWORD, lead_id_from_token
from app.services.landing_analytics import (
    browser_of,
    classify_traffic,
    clip,
    device_of,
    fold_events,
    geo_of,
    in_app_of,
    merge_values,
    new_events,
    os_of,
    referrer_host_of,
    source_of,
)
from app.services.lead_notify import send_new_lead_notice
from app.services.media_public import parse_range, read_range, resolve_public_media
from app.services.tenant_context import set_org_id
from app.services.tenant_resolver import WebhookOrgUnresolved, webhook_org_or_refuse

log = logging.getLogger(__name__)
router = APIRouter()

TURNSTILE_VERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify"

# What a landing session key looks like: 32 hex characters, generated by the
# page. Enforced by the beacon's schema (a malformed one there is a client bug
# and there is nothing to lose by refusing it) and merely *checked* on the
# capture path, where refusing would cost a lead.
_SESSION_KEY = re.compile(r"[0-9a-f]{32}")

# ── Rate limiting ────────────────────────────────────────────────────────
# Two windows, and the second is the one that matters. A per-IP limit alone is
# decorative behind a proxy: the client IP is read from a header, and anyone
# willing to rotate that header has an unlimited per-IP budget. The global
# ceiling is what bounds the damage regardless of how many identities the
# caller invents.
#
# In-process counters are correct here only because the app is pinned to a
# single uvicorn worker — the same constraint main.py documents for the three
# background loops. Under `--workers N` these become N independent budgets and
# belong in Redis alongside those loops.
PER_IP_LIMIT = 5
PER_IP_WINDOW = 600.0
GLOBAL_LIMIT = 60
GLOBAL_WINDOW = 600.0
# Bounded so a flood of distinct (or forged) addresses cannot grow the map
# without limit — the memory itself would otherwise be the attack.
MAX_TRACKED_IPS = 5_000

_hits: dict[str, deque[float]] = {}
_global_hits: deque[float] = deque()

# The landing beacons get their OWN budget, and that is the whole point of
# these four constants existing beside the four above rather than reusing them.
# One ordinary visit sends a page view, a section view, a scroll depth and
# maybe a tap — four attempts against a per-address budget of five. Sharing the
# counters would mean a visitor who reads the page attentively can no longer
# submit the form, which is precisely backwards.
#
# The numbers are high because the work is small (one upsert and a few inserts,
# no captcha call, no outbound mail) and low enough that a script cannot fill
# the table from one address unattended.
EVENTS_PER_IP_LIMIT = 60
EVENTS_PER_IP_WINDOW = 600.0
EVENTS_GLOBAL_LIMIT = 3_000
EVENTS_GLOBAL_WINDOW = 600.0
# 16 KB: a full batch of 25 events, each with its metadata, plus the attribution
# and the referrer, fits with room to spare — and it is sixteen times tighter
# than the 256 KB every other route gets by default.
EVENTS_MAX_BODY = 16_384
EVENTS_MAX_PER_BATCH = 25

_ev_hits: dict[str, deque[float]] = {}
_ev_global_hits: deque[float] = deque()

# And the partner brief gets a THIRD budget, for the same reason the beacons
# got a second one: the people who open it are the two agents this install
# exists for, and a budget shared with lead capture would mean Natalia
# re-reading the page on a bad signal is what stops a seller's form from being
# written. Backwards in exactly the way the comment above describes.
#
# Generous per address because the page autosaves as they type — a careful pass
# through nine names is easily forty saves — and bounded globally because the
# token is the only credential: somebody who has a link must not be able to
# spend the install's capacity with it.
BRIEF_PER_IP_LIMIT = 120
BRIEF_PER_IP_WINDOW = 600.0
BRIEF_GLOBAL_LIMIT = 1_200
BRIEF_GLOBAL_WINDOW = 600.0
# 64 KB. The answers are nine short verdicts and a handful of free-text notes;
# this is two orders of magnitude more than that and still small enough that
# the column can never become somebody's file store.
BRIEF_MAX_ANSWERS = 65_536

_brief_hits: dict[str, deque[float]] = {}
_brief_global_hits: deque[float] = deque()

# A beacon endpoint that logs per request is an amplifier: the cheapest way to
# fill an operator's disk would be to send it rubbish. These remember the last
# day each condition was reported, so a flood produces one line, not a million.
_global_warned: dict[object, date] = {}
_reject_warned: dict[object, date] = {}
_cap_warned: dict[object, date] = {}


def _warn_once(seen: dict[object, date], key: object, message: str) -> None:
    today = datetime.now(UTC).date()
    if seen.get(key) == today:
        return
    seen[key] = today
    log.warning("%s", message)


def _path_only(path: str | None) -> str | None:
    """The path with any query string removed.

    The tracker sends `location.pathname`, but a client is a client: if one
    ever sends `pathname + search`, a URL carrying an email address in a
    parameter would land verbatim in a column, against the promise that nothing
    identifying is stored. Cut here, where it cannot be forgotten.
    """
    cleaned = clip(path)
    if cleaned is None:
        return None
    return cleaned.split("?", 1)[0].split("#", 1)[0] or "/"


def _prune(window: deque[float], now: float, span: float) -> None:
    while window and now - window[0] > span:
        window.popleft()


def _charge_ip(
    store: dict[str, deque[float]], ip: str, limit: int, span: float, now: float | None
) -> bool:
    """Charge one address against a bounded per-address budget."""
    stamp = time.monotonic() if now is None else now
    window = store.get(ip)
    if window is None:
        if len(store) >= MAX_TRACKED_IPS:
            # Drop the coldest tracked address rather than refuse service.
            coldest = min(store, key=lambda k: store[k][-1] if store[k] else 0.0)
            store.pop(coldest, None)
        window = store[ip] = deque()
    _prune(window, stamp, span)
    if len(window) >= limit:
        return True
    window.append(stamp)
    return False


def _ip_limited(ip: str, now: float | None = None) -> bool:
    """Charge this address for a capture attempt; say whether it is over budget.

    Charged for EVERY attempt that reaches it, including honeypot hits and
    submissions the captcha will reject. The budget is per address and bounded,
    so spending it on refused work costs the caller and nobody else.
    """
    return _charge_ip(_hits, ip, PER_IP_LIMIT, PER_IP_WINDOW, now)


def _ev_ip_limited(ip: str, now: float | None = None) -> bool:
    """The same, against the beacons' own budget. See EVENTS_PER_IP_LIMIT."""
    return _charge_ip(_ev_hits, ip, EVENTS_PER_IP_LIMIT, EVENTS_PER_IP_WINDOW, now)


def _global_limited(now: float | None = None) -> bool:
    """Charge the platform-wide budget, and say whether it is exhausted.

    Deliberately charged LAST — after the honeypot, after the per-IP budget and
    after the captcha. It used to be charged first, which made it a kill switch
    anyone could hold down: sixty tokenless posts from sixty forged addresses
    were each refused with 400 and each still consumed a slot, so the captcha
    that is supposed to be the defence a script cannot outspend was bypassed
    for availability, and every agency on the install lost lead capture for ten
    minutes. Now a request only spends this budget once it has proven it is
    worth writing.
    """
    stamp = time.monotonic() if now is None else now
    _prune(_global_hits, stamp, GLOBAL_WINDOW)
    if len(_global_hits) >= GLOBAL_LIMIT:
        return True
    _global_hits.append(stamp)
    return False


def _brief_ip_limited(ip: str, now: float | None = None) -> bool:
    """Charge this address against the brief budget. See BRIEF_PER_IP_LIMIT."""
    return _charge_ip(_brief_hits, ip, BRIEF_PER_IP_LIMIT, BRIEF_PER_IP_WINDOW, now)


def _brief_global_limited(now: float | None = None) -> bool:
    """Charge the platform-wide brief budget. Its own, never capture's."""
    stamp = time.monotonic() if now is None else now
    _prune(_brief_global_hits, stamp, BRIEF_GLOBAL_WINDOW)
    if len(_brief_global_hits) >= BRIEF_GLOBAL_LIMIT:
        return True
    _brief_global_hits.append(stamp)
    return False


def _ev_global_limited(now: float | None = None) -> bool:
    """Charge the platform-wide beacon budget. Separate from capture's, so a
    flood of beacons can never be what stops a lead from being written."""
    stamp = time.monotonic() if now is None else now
    _prune(_ev_global_hits, stamp, EVENTS_GLOBAL_WINDOW)
    if len(_ev_global_hits) >= EVENTS_GLOBAL_LIMIT:
        return True
    _ev_global_hits.append(stamp)
    return False


def reset_rate_limits() -> None:
    """Test seam. Nothing in the app calls this."""
    _hits.clear()
    _global_hits.clear()
    _ev_hits.clear()
    _ev_global_hits.clear()
    _brief_hits.clear()
    _brief_global_hits.clear()


def client_ip(request: Request) -> str:
    """The visitor's address, as well as it can be known.

    `CF-Connecting-IP` first: Cloudflare overwrites it on every request, so a
    client cannot forge it through the tunnel this install actually runs behind.
    `X-Forwarded-For` is next and is only as trustworthy as whatever set it —
    hence the global ceiling above, which does not depend on any of this being
    honest.
    """
    return _client_ip_parts(request)[0]


def _client_ip_parts(request: Request) -> tuple[str, bool]:
    """(address, came_from_a_proxy_header).

    The flag matters for Turnstile. When neither header is present the socket
    peer is NOT the visitor: the POST is proxied by the Next.js server through
    its `/api/*` rewrite, so `request.client.host` is the frontend container's
    address on the Docker bridge. Sending that to Cloudflare as `remoteip` is a
    classic source of spurious verification failures — the field is optional,
    and omitting it is better than asserting something false.
    """
    cf = (request.headers.get("cf-connecting-ip") or "").strip()
    if cf:
        return cf[:45], True
    forwarded = (request.headers.get("x-forwarded-for") or "").split(",")[0].strip()
    if forwarded:
        return forwarded[:45], True
    return (request.client.host if request.client else "unknown")[:45], False


async def _turnstile_ok(token: str | None, ip: str | None) -> bool:
    """Verify a Turnstile token, or pass when no secret is configured.

    Configured-but-unreachable fails CLOSED. A captcha that waves everyone
    through whenever Cloudflare has a bad minute is not a captcha, and this is
    the only defence here that a determined script cannot simply outspend.
    """
    secret = (get_settings().TURNSTILE_SECRET or "").strip()
    if not secret:
        return True
    if not token:
        return False
    payload = {"secret": secret, "response": token}
    if ip:
        payload["remoteip"] = ip
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.post(TURNSTILE_VERIFY_URL, data=payload)
            return bool(response.json().get("success"))
    except Exception as exc:  # noqa: BLE001
        log.error("Turnstile verification failed to complete: %s", exc)
        return False


class CalculatorIn(BaseModel):
    """What the visitor typed on /calculator, and the sliders they moved.

    Inputs and overrides only — never the result. The server recomputes it
    (`services/calculator.build_snapshot`) before anything is stored, so a
    browser cannot file "$2,000,000" beside a $900 rent.

    Validated INSIDE the route, not by the envelope: a calculation that fails
    these bounds is dropped with a warning and the lead is captured anyway.
    The `session_id` comment below says why in the analytics' words — a
    pattern on the envelope turns a page bug into a lost person — and a
    calculator is a courtesy, the lead is the point. `extra="forbid"` so an
    unknown key drops the calculation rather than riding along unnoticed.
    """

    model_config = ConfigDict(extra="forbid")

    rent: float = Field(gt=0, le=50_000)
    savings: float = Field(ge=0, le=5_000_000)
    credit: Literal["excellent", "good", "fair"]
    appreciation: float | None = Field(default=None, ge=-0.10, le=0.15)
    rent_growth: float | None = Field(default=None, ge=-0.10, le=0.15)
    rate: float | None = Field(default=None, ge=0.0, le=0.20)
    hoa_monthly: float | None = Field(default=None, ge=0, le=5_000)
    # The horizon selector on the page (5/10/15/20/30). The upper bound is
    # imported rather than typed so it cannot drift away from the scan the
    # comparison actually performs. `extra="forbid"` above is why this field has
    # to exist at all: without it the browser's `years` would not be ignored, it
    # would drop the WHOLE calculation — worse than the bug it fixes.
    years: int | None = Field(default=None, ge=1, le=MAX_YEARS)
    lang: Literal["en", "es"] | None = None


class PublicLeadIn(BaseModel):
    # The public key of the form, as configured in channel_routes. Optional:
    # a single-agency install has nothing to disambiguate, and requiring a key
    # there would mean every customer must run a platform API call before their
    # own contact form works.
    form: str | None = Field(default=None, max_length=254)
    name: str | None = Field(default=None, max_length=MAX_NAME)
    email: str | None = Field(default=None, max_length=254)
    phone: str | None = Field(default=None, max_length=40)
    message: str | None = Field(default=None, max_length=MAX_MESSAGE)
    consent: bool = False
    consent_text: str | None = Field(default=None, max_length=MAX_CONSENT_TEXT)
    utm: dict[str, str] | None = None
    # The landing page's own visit key, when the tracker is running. Its only
    # job is to join this submission to the session that produced it, which is
    # what turns "we got a lead" into "the visit that became this lead came
    # from TikTok, read three sections and tapped call first".
    #
    # A separate field rather than an attribution key on purpose: the whitelist
    # in `capture.py` means "which campaign produced this lead". For a lead
    # born in this submission, the validated key is stored separately as a
    # private acquisition-session marker; later submissions never replace it.
    #
    # Deliberately NOT pinned to the session-key shape here, unlike the beacon's
    # own field. A `pattern` on this model rejects the whole submission with
    # 422, so a bug in the tracker's key generator would stop costing an
    # analytics row and start costing the LEAD — the exact inversion the link
    # below is written to avoid. Bounded only, and checked for shape at the
    # point of use, where a bad value is simply not looked up.
    session_id: str | None = Field(default=None, max_length=64)
    # Positive browser evidence only. False and absence mean "unknown", never
    # "human"; the server combines this with its own user-agent and the exact
    # QA UTM pair before the lead is written.
    webdriver: Literal[True] | None = None
    # The same marker the beacon carries, so a submission we make while testing
    # the form does not arrive in the CRM looking like a customer.
    qa: Literal[True] | None = None
    turnstile_token: str | None = Field(default=None, max_length=4_000)
    # Honeypot. Named for something a browser autofill would plausibly target
    # and hidden in the markup, so a human never sees it and a bot fills it in.
    website: str | None = Field(default=None, max_length=200)
    # Present only when the form sits under /calculator. Travels as its own
    # field, not as an attribution key: the whitelist in `capture.py` means
    # "which campaign produced this lead" and is pinned by tests; a
    # calculation is not that.
    #
    # `Any`, deliberately: `CalculatorIn` is applied in the handler so that a
    # malformed calculation can never make this envelope a 422 — see
    # `CalculatorIn` for why the lead must survive it.
    calculator: Any = None

    # No trimming validator here, deliberately, and it took writing one to find
    # out why: `services/capture.py` already normalises every field that is
    # stored — `clean_text` for name and message (which trims AND collapses
    # runs of whitespace), `normalize_email` and `normalize_phone` for the
    # other two. A validator on this model changed nothing that reached the
    # database; measured on identical POSTs, the stored row was byte-identical
    # with and without it. Code that does nothing is worse than absent: it
    # reads as coverage.
    #
    # Two fields must never acquire one, which is the part worth writing down:
    #
    # - `website` is the honeypot, tested below as `if body.website` — before
    #   the captcha and before tenant resolution. A whitespace-only value is
    #   truthy, so a bot filling the hidden field with spaces is caught today.
    #   Trimming it to None would wave that bot straight through.
    # - `consent_text` reaches `clean_text` like the rest, so it is already
    #   collapsed rather than stored verbatim. Worth knowing before anyone
    #   relies on it reading back exactly as the person saw it.


async def _claim_landing_session(
    db: AsyncSession,
    *,
    org_id: int,
    session_key: str,
    lead_id: int,
    request: Request,
    attribution: dict[str, str],
    traffic_class: str,
    traffic_class_reason: str | None,
) -> None:
    now = datetime.now(UTC)
    referrer_host = referrer_host_of(attribution.get("referrer"))
    user_agent = request.headers.get("user-agent")
    country, region, city = geo_of(request.headers)
    statement = pg_insert(LandingSession).values(
        org_id=org_id,
        session_key=session_key,
        first_seen_at=now,
        last_seen_at=now,
        utm_source=attribution.get("utm_source"),
        utm_medium=attribution.get("utm_medium"),
        utm_campaign=attribution.get("utm_campaign"),
        utm_content=attribution.get("utm_content"),
        utm_term=attribution.get("utm_term"),
        referrer_host=referrer_host,
        source=source_of(attribution.get("utm_source"), referrer_host),
        traffic_class=traffic_class,
        traffic_class_reason=traffic_class_reason,
        traffic_classified_at=now,
        device=device_of(user_agent),
        browser=browser_of(user_agent),
        os=os_of(user_agent),
        in_app=in_app_of(user_agent),
        country=country,
        region=region,
        city=city,
        lead_id=lead_id,
        form_submitted_at=now,
    )
    await db.execute(
        statement.on_conflict_do_update(
            index_elements=["org_id", "session_key"],
            set_={
                "lead_id": lead_id,
                "form_submitted_at": now,
                "updated_at": func.now(),
            },
            where=LandingSession.lead_id.is_(None),
        )
    )


@router.post("/leads", status_code=202)
async def capture(
    body: PublicLeadIn, request: Request, db: AsyncSession = Depends(get_db)
) -> dict[str, bool]:
    ip, ip_is_from_a_proxy_header = _client_ip_parts(request)

    # ── Order matters, and each step is placed for a reason ──────────────
    # 1. Per-IP budget first, charged even for the honeypot. It used to sit
    #    AFTER the honeypot branch, so `{"website": "bot"}` was an unmetered
    #    endpoint: two hundred consecutive posts all answered 202 and left
    #    every counter untouched.
    if _ip_limited(ip):
        log.warning("Rate limit refused a capture from %s", ip)
        raise HTTPException(status_code=429, detail="too_many_requests")

    if body.website:
        # Answer exactly like a good submission. Telling a bot it was detected
        # is free tuning feedback for whoever wrote it.
        log.info("Honeypot tripped from %s", ip)
        return {"ok": True}

    # 2. Shape of the submission, BEFORE the tenant is resolved. A probe with
    #    no email and no phone used to return 422 for a live form key and 404
    #    for a dead one, which made this a quiet enumeration oracle: unlike a
    #    202 probe it writes no lead, so a scan left no trace anywhere the
    #    operator looks. Same answer now regardless of the key.
    # The calculation, bounded here and dropped — not the lead — when it
    # fails. Nothing of the payload is logged; the shape of the failure is.
    calculator: dict | None = None
    if body.calculator is not None:
        try:
            calculator = CalculatorIn.model_validate(body.calculator).model_dump()
        except ValidationError as exc:
            log.warning(
                "Calculator payload refused (%d problem(s)); lead still captured",
                len(exc.errors()),
            )

    gpc = request.headers.get("sec-gpc") == "1"
    submitted_attribution = {} if gpc else (body.utm or {})
    cleaned_attribution = clean_attribution(submitted_attribution)
    traffic_class, traffic_class_reason = (
        ("unknown", None)
        if gpc
        else classify_traffic(
            request.headers.get("user-agent"),
            body.webdriver is True,
            cleaned_attribution,
            body.qa is True,
        )
    )
    analytics_session_id = (
        body.session_id
        if (
            _SESSION_KEY.fullmatch(body.session_id or "")
            and get_settings().LANDING_EVENTS_ENABLED
            and not gpc
        )
        else None
    )
    submission = FormSubmission(
        name=body.name,
        email=body.email,
        phone=body.phone,
        message=body.message,
        consent=body.consent,
        consent_text=body.consent_text,
        attribution=submitted_attribution,
        traffic_class=traffic_class,
        traffic_class_reason=traffic_class_reason,
        landing_session_key=analytics_session_id,
        ip=ip,
        user_agent=request.headers.get("user-agent"),
        calculator=calculator,
    )
    try:
        validate_submission(submission)
    except CaptureRejected as exc:
        raise HTTPException(status_code=422, detail=exc.code) from exc

    # A lead we cannot reach is not a lead. Every field on this form is optional,
    # which was correct while there were two automatic channels; SMS is not one
    # of them today (Twilio accepts and the carrier drops it — error 30034,
    # measured), so a phone-only submission produces a row nobody can answer.
    # Refusing it in front of the person, while they are still on the page and
    # can add an address, is better than accepting it and going quiet.
    #
    # After the captcha check would be wrong: this costs nothing to evaluate and
    # tells an honest visitor what to fix, whereas a bot never gets this far.
    if get_settings().CAPTURE_REQUIRE_EMAIL and not (submission.email or "").strip():
        raise HTTPException(status_code=422, detail="email_required")

    # 3. Captcha before the global budget is touched. A request the captcha
    #    will refuse must not be able to spend a slot: that turned the ceiling
    #    into a kill switch anyone could hold down without solving anything.
    if not await _turnstile_ok(
        body.turnstile_token, ip if ip_is_from_a_proxy_header else None
    ):
        raise HTTPException(status_code=400, detail="captcha_failed")

    # 4. The platform-wide budget, charged BEFORE the tenant lookup rather than
    #    after it. Resolving a form key is a database round trip, and with the
    #    charge at the end a caller rotating the IP header could drive an
    #    unbounded number of them: the per-IP budget resets with every forged
    #    address, so nothing counted the work. Charging here means the ceiling
    #    bounds real work, not just successful writes.
    if _global_limited():
        log.error(
            "Global capture ceiling reached — lead capture is refused for "
            "every agency until the window clears. If this is not a flood, "
            "raise GLOBAL_LIMIT; if it is, configure TURNSTILE_SECRET."
        )
        raise HTTPException(status_code=429, detail="too_many_requests")

    try:
        org_id = await webhook_org_or_refuse(
            CHANNEL_WEB,
            body.form,
            # A key that was supplied must match a route. Without this, an
            # agency offboarded the ordinary way — suspend, delete routes —
            # leaves a live landing page whose submissions get filed into
            # whichever agency remains.
            fallback_when_unmapped=not body.form,
        )
    except WebhookOrgUnresolved as exc:
        # 404, not 503. The form key is public — it ships in the landing page —
        # but the set of valid keys is not, and a distinguishable error turns
        # this endpoint into an oracle for enumerating an operator's tenants.
        log.error("refusing web capture — %s", exc)
        raise HTTPException(status_code=404, detail="unknown_form") from exc

    set_org_id(org_id)

    try:
        captured = await capture_lead(submission, db)
    except CaptureRejected as exc:
        await db.rollback()
        raise HTTPException(status_code=422, detail=exc.code) from exc
    except Exception:
        await db.rollback()
        log.exception("Web capture failed")
        raise HTTPException(status_code=500, detail="capture_failed") from None

    await db.commit()

    # Join the visit to the lead it produced. Wrapped after the lead commit
    # because this is analytics: the lead is already durable, and a failure
    # here must cost a row in a report, never a 500 that sends the
    # visitor round the submit button a second time. This is an upsert because
    # the POST can arrive before the first beacon; the unique session key makes
    # either arrival order converge on one row.
    if (
        analytics_session_id
        and captured.get("lead_id")
    ):
        try:
            await _claim_landing_session(
                db,
                org_id=org_id,
                session_key=analytics_session_id,
                lead_id=int(captured["lead_id"]),
                request=request,
                attribution=cleaned_attribution,
                traffic_class=traffic_class,
                traffic_class_reason=traffic_class_reason,
            )
            await db.commit()
        except Exception as exc:  # noqa: BLE001
            log.warning("Could not link landing session to lead: %s", exc)
            try:
                await db.rollback()
            except Exception:  # noqa: BLE001
                # The rollback is a courtesy — the lead is already durable and
                # the session is about to be discarded either way. Letting this
                # escape would turn an analytics failure into a 500 on a
                # submission that already succeeded, which is the one outcome
                # this whole block exists to prevent.
                log.warning("Rollback after the link failure also failed")

    # After the commit, on purpose: the lead must be durable before anyone is
    # told about it, and a notification failure must cost the notification,
    # never the capture. Duplicates are already filtered — a double-submit
    # returns status "duplicate" above and must not email the agency twice.
    if captured.get("status") == "ok":
        await send_new_lead_notice(captured["lead_id"], captured.get("message_id"))
        # And the visitor gets their own numbers back, when they left any. Inside
        # the same `"ok"` branch on purpose: a duplicate submission must not
        # email them twice, and the status above is already the only place that
        # knows. Sends nothing at all until `POSTAL_ADDRESS` is configured — it
        # says so in the log rather than failing.
        await send_calculator_breakdown(captured["lead_id"])

    # Deliberately says nothing about whether the lead was new, merged or
    # duplicate: that is a membership oracle for anyone who wants to test
    # whether an address is in an agency's book.
    return {"ok": True}


# ── Landing analytics ────────────────────────────────────────────────────


class LandingEventIn(BaseModel, extra="forbid"):
    t: str = Field(max_length=40)
    meta: dict[str, Any] | None = None

    @field_validator("t")
    @classmethod
    def _known(cls, v: str) -> str:
        if v not in LANDING_EVENT_TYPES:
            raise ValueError("unknown event type")
        return v

    @field_validator("meta")
    @classmethod
    def _small(cls, v: dict[str, Any] | None) -> dict[str, Any] | None:
        """Bounded in both directions: at most five keys, and values that are
        short strings or plain numbers. The metadata is a label — which section,
        which percentage, which button — and anything larger arriving here is
        somebody using a public endpoint as free storage."""
        if v is None:
            return None
        if len(v) > 5:
            raise ValueError("too many metadata keys")
        out: dict[str, Any] = {}
        for key, value in v.items():
            if not isinstance(key, str) or len(key) > 40:
                raise ValueError("bad metadata key")
            if isinstance(value, bool) or value is None:
                continue
            if isinstance(value, int):
                out[key] = value
            elif isinstance(value, str):
                trimmed = value.strip()[:120]
                if trimmed:
                    out[key] = trimmed
            else:
                raise ValueError("bad metadata value")
        return out


class LandingBatchIn(BaseModel, extra="forbid"):
    form: str | None = Field(default=None, max_length=254)
    # Random, client-side, and it dies with the tab. Pinned to a shape so a row
    # key can never be an arbitrary string somebody chose.
    session: str = Field(pattern=r"^[0-9a-f]{32}$")
    path: str | None = Field(default=None, max_length=200)
    lang: Literal["en", "es"] | None = None
    screen_w: int | None = Field(default=None, ge=0, le=10_000)
    webdriver: Literal[True] | None = None
    # This browser was marked as one of ours, once, and remembers it. The model
    # forbids extra keys, so the beacon would 422 without this line.
    qa: Literal[True] | None = None
    utm: dict[str, str] | None = None
    referrer: str | None = Field(default=None, max_length=500)
    events: list[LandingEventIn] = Field(min_length=1, max_length=EVENTS_MAX_PER_BATCH)


@router.post("/landing")
async def landing_events(request: Request, db: AsyncSession = Depends(get_db)) -> Response:
    """What a visitor did on the marketing page, before there was a lead.

    Unauthenticated and uncaptcha'd, because it is sent by a page anyone can
    open and by `navigator.sendBeacon`, which cannot solve a challenge and
    cannot wait for one. Three things stand in for the captcha, and the third
    is the one that actually bounds the table: its own rate budget, a 16 KB
    body of at most 25 events with a closed set of names, and a **per-agency
    daily cap on new sessions**. Without that cap the rate limit bounds the
    speed of writing permanent rows and nothing bounds their number.

    Always 204, even when it declines to do anything. The sender has nothing
    useful to do with the distinction, and a public endpoint that answers
    differently for a valid and an invalid form key is an oracle for
    enumerating an operator's tenants. Honest caveat, since a comment that
    overclaims is worse than none: the STATUS is identical, but a resolvable
    key does more work than an unresolvable one, so the two are distinguishable
    by timing to anyone willing to average enough samples.

    The body is read and parsed by hand rather than declared as a Pydantic
    parameter because `sendBeacon` sends `text/plain` — Chromium refuses a JSON
    Blob from a beacon in some contexts — and FastAPI would answer a valid
    batch with 422 purely over the content type.
    """
    if request.headers.get("sec-gpc") == "1":
        return Response(status_code=204)

    ip = client_ip(request)
    if _ev_ip_limited(ip):
        return Response(status_code=429)

    # Charged BEFORE the body is read and parsed. The sibling endpoint carries
    # a comment about the opposite order being a past outage, and the reasoning
    # inverts here: `capture` charges last so a request the captcha will refuse
    # cannot spend the platform's budget. There is no captcha on this path, so
    # a caller rotating the client-IP header would otherwise buffer 16 KB and
    # run a JSON parse per request without ever touching the ceiling.
    if _ev_global_limited():
        _warn_once(_global_warned, "landing", "Landing beacon ceiling reached")
        return Response(status_code=429)

    raw = await request.body()
    if len(raw) > EVENTS_MAX_BODY:
        return Response(status_code=413)
    try:
        payload = json.loads(raw) if raw else None
        body = LandingBatchIn.model_validate(payload)
    except Exception as exc:  # noqa: BLE001
        # 400 for both a malformed body and one that fails validation — the
        # sender is our own script and a distinguishing error helps nobody but
        # somebody probing the schema. But it is LOGGED, once per window: the
        # tracker is the only caller, so a schema drift on its side would make
        # every batch 400 and leave the table at zero with nothing anywhere
        # saying why, and `sendBeacon` has no error handler to notice.
        _warn_once(_reject_warned, "landing", f"Landing beacon rejected: {exc}")
        return Response(status_code=400)

    if not get_settings().LANDING_EVENTS_ENABLED:
        return Response(status_code=204)

    try:
        org_id = await webhook_org_or_refuse(
            CHANNEL_WEB, body.form, fallback_when_unmapped=not body.form
        )
    except WebhookOrgUnresolved as exc:
        log.info("Dropping landing beacon — %s", exc)
        return Response(status_code=204)

    # Bound BEFORE the first query on `db`: the org id is injected into the
    # transaction when it begins, so a query issued before this point runs with
    # an empty `app.current_org_id` and, under default-deny RLS, sees nothing.
    set_org_id(org_id)

    now = datetime.now(UTC)
    batch = [(e.t, e.meta or {}) for e in body.events]

    try:
        session_id = await _landing_session_id(db, org_id, body, request, now)
        if session_id is None:
            return Response(status_code=204)

        await db.execute(
            update(LandingSession)
            .where(LandingSession.id == session_id)
            .values(
                **merge_values(fold_events(batch), now),
                # A successful form POST can win the race and create the
                # session before this first beacon. Preserve that POST's
                # first-touch attribution while filling the page context that
                # only the beacon carries.
                landing_path=func.coalesce(
                    LandingSession.landing_path, _path_only(body.path)
                ),
                lang=func.coalesce(LandingSession.lang, body.lang),
                screen_w=func.coalesce(LandingSession.screen_w, body.screen_w),
            )
        )
        db.add_all(new_events(org_id, session_id, batch, now))
        await db.commit()
    except Exception:
        await db.rollback()
        log.exception("Landing beacon failed")
        # Still 204: the page must not learn anything from a failure here, and
        # a beacon has nobody to report to.
        return Response(status_code=204)

    return Response(status_code=204)


async def _landing_session_id(
    db: AsyncSession,
    org_id: int,
    body: LandingBatchIn,
    request: Request,
    now: datetime,
) -> int | None:
    """The id of this visit's session row, creating it if this is its first
    beacon. None when the agency has already opened its quota of sessions
    today, which is the only thing bounding how many permanent rows an
    anonymous caller can create.

    The cap is on CREATION, not on beacons: a visit already recorded keeps
    merging, so a real visitor is never truncated mid-page — only a caller
    inventing session keys is stopped.
    """
    found = (
        await db.execute(
            select(LandingSession.id).where(
                LandingSession.org_id == org_id,
                LandingSession.session_key == body.session,
            )
        )
    ).scalar_one_or_none()
    if found is not None:
        return found

    if await _sessions_today(db, org_id, now) >= get_settings().LANDING_SESSIONS_PER_DAY:
        _warn_once(
            _cap_warned,
            org_id,
            f"Landing session cap reached for organization {org_id}; new visits "
            "are not being recorded until tomorrow",
        )
        return None

    attribution = clean_attribution(body.utm)
    host = referrer_host_of(body.referrer)
    ua = request.headers.get("user-agent")
    traffic_class, traffic_class_reason = classify_traffic(
        ua, body.webdriver is True, attribution, body.qa is True
    )
    country, region, city = geo_of(request.headers)

    # Core INSERT, not the ORM: `before_flush` is what stamps `org_id` on this
    # project's tables, and it never sees a Core statement. Hence the explicit
    # value — without it the policy's WITH CHECK refuses the row.
    inserted = (
        await db.execute(
            pg_insert(LandingSession)
            .values(
                org_id=org_id,
                session_key=body.session,
                first_seen_at=now,
                last_seen_at=now,
                landing_path=_path_only(body.path),
                lang=body.lang,
                utm_source=attribution.get("utm_source"),
                utm_medium=attribution.get("utm_medium"),
                utm_campaign=attribution.get("utm_campaign"),
                utm_content=attribution.get("utm_content"),
                utm_term=attribution.get("utm_term"),
                referrer_host=host,
                source=source_of(attribution.get("utm_source"), host),
                traffic_class=traffic_class,
                traffic_class_reason=traffic_class_reason,
                traffic_classified_at=now,
                device=device_of(ua),
                browser=browser_of(ua),
                os=os_of(ua),
                in_app=in_app_of(ua),
                country=country,
                region=region,
                city=city,
                screen_w=body.screen_w,
            )
            # First touch wins, exactly as it does for a lead's attribution: a
            # visitor who reloads with a different query string has not changed
            # where they came from. Also the race: two first beacons for one
            # visit, and the loser reads the winner's row below.
            .on_conflict_do_nothing(index_elements=["org_id", "session_key"])
            .returning(LandingSession.id)
        )
    ).scalar_one_or_none()
    if inserted is not None:
        return inserted

    return (
        await db.execute(
            select(LandingSession.id).where(
                LandingSession.org_id == org_id,
                LandingSession.session_key == body.session,
            )
        )
    ).scalar_one_or_none()


async def _sessions_today(db: AsyncSession, org_id: int, now: datetime) -> int:
    """How many visits this agency has opened since local midnight.

    Local, not UTC, because every number this feature produces is read against
    the agency's own day and a cap that resets at 5pm Denver time would be
    surprising in exactly the way an operator does not need. Counted through a
    LIMIT so the scan stops at the cap instead of walking a busy day's rows.
    """
    cap = get_settings().LANDING_SESSIONS_PER_DAY
    zone = await _agency_zone(db)
    midnight = now.astimezone(zone).replace(hour=0, minute=0, second=0, microsecond=0)
    window = (
        select(LandingSession.id)
        .where(
            LandingSession.org_id == org_id,
            LandingSession.first_seen_at >= midnight.astimezone(UTC),
        )
        .limit(cap)
        .subquery()
    )
    return (
        await db.execute(select(func.count()).select_from(window))
    ).scalar_one()


async def _agency_zone(db: AsyncSession):
    """The acting agency's timezone, or UTC if it has not set a usable one."""
    from app.models import AgentSettings
    from app.services.timezones import resolve_zone

    name = (
        await db.execute(select(AgentSettings.timezone).limit(1))
    ).scalar_one_or_none()
    return resolve_zone(name or "") or UTC


@router.api_route("/content/{piece_id}/media", methods=["GET", "HEAD"])
async def public_media(request: Request, piece_id: int):
    """The video, for the platform that is about to post it.

    Unauthenticated because Buffer has no session and cannot get one: it takes
    a URL and downloads from it when the post goes out. The gate is the piece's
    status, not the address — see `services/media_public.py` for why the signed
    link this repo would otherwise reach for cannot work here.

    Range requests are answered here rather than left to `FileResponse`, which
    in this Starlette version ignores them and returns the whole file with a
    200. Media fetchers ask for ranges, and a client that insists would see a
    broken video hours after the post was created.

    **HEAD as well as GET, and that is not tidiness.** Starlette's own `Route`
    adds HEAD to anything that answers GET; FastAPI's `APIRoute` does not, so
    `@router.get` alone returns 405 to a HEAD. Buffer asks HEAD first to see
    whether the media is really there, and on the 405 gave up with "Video could
    not be read from its URL" — a message that points at the file, the URL and
    the tunnel, none of which were the problem. Measured on the first real
    publish attempt: `HEAD /api/v1/public/content/3/media 405`.
    """
    path = await resolve_public_media(piece_id)
    if path is None:
        # The same answer for "no such piece", "not approved" and "file gone".
        raise HTTPException(status_code=404, detail="Not found")

    size = path.stat().st_size
    # Nothing in between may keep a copy: an edit revokes the piece's approval,
    # and a cached body would outlive that decision.
    headers = {"Cache-Control": "no-store", "Accept-Ranges": "bytes"}

    if request.method == "HEAD":
        # The headers a fetcher is asking for, and no body — the point of the
        # request is to learn the size and type before spending the download.
        return Response(
            status_code=200,
            media_type="video/mp4",
            headers={**headers, "Content-Length": str(size)},
        )

    try:
        span = parse_range(request.headers.get("range"), size)
    except ValueError:
        # Saying so, rather than sending bytes nobody asked for and letting the
        # client believe it got what it wanted.
        return Response(
            status_code=416, headers={**headers, "Content-Range": f"bytes */{size}"}
        )

    if span is None:
        return FileResponse(path, media_type="video/mp4", headers=headers)

    first, last = span
    return StreamingResponse(
        read_range(path, first, last),
        status_code=206,
        media_type="video/mp4",
        headers={
            **headers,
            "Content-Range": f"bytes {first}-{last}/{size}",
            "Content-Length": str(last - first + 1),
        },
    )


# ── The partner brief ────────────────────────────────────────────────────
# A page we hand to the two agents this install is built for, reached by a link
# and answered by tapping. No session, because the whole point is that somebody
# who does not work inside this product can answer without one; the token in
# the path is the credential.
#
# That makes this the fourth caller with login's problem — it must find an
# organization *before* an organization is known — and it is solved login's
# way, not by widening anything: the bypass engine maps token → org and does
# nothing else, and every read and write after that runs on the ordinary
# RLS-enforcing session inside that org. A bug in the queries below can
# therefore leak one tenant's brief at worst, never the table.

# `secrets.token_urlsafe` output: base64url, no padding. Checked before the
# database is touched so a flood of rubbish costs a regex and not a round trip
# — and answered identically to a well-formed token that does not exist, so
# this cannot be used to learn what a real one looks like.
_BRIEF_TOKEN = re.compile(r"[A-Za-z0-9_-]{16,64}")


class BriefAnswersIn(BaseModel):
    """What the page saves. Deliberately unshaped beyond this.

    `answers` is whatever that brief's page decided to collect, because the
    briefs differ from one week to the next and a schema here would have to be
    migrated for every question we think of. It is bounded by size rather than
    by shape — see BRIEF_MAX_ANSWERS — which is the property that actually
    protects the column.
    """

    model_config = ConfigDict(extra="forbid")

    answers: dict[str, Any] = Field(default_factory=dict)
    #: True when a person pressed the button, false when the page autosaved.
    #: See `_should_notify` for why the difference has to reach the server.
    notify: bool = False


async def _brief_org(token: str) -> tuple[int, int] | None:
    """Map a token to `(brief id, org id)`, or None.

    The only query in this module that runs outside a tenant, and it reads two
    integers. Keeping it that small is what keeps the bypass justified.
    """
    async with get_bypass_session_factory()() as meta:
        row = (
            await meta.execute(
                select(PartnerBrief.id, PartnerBrief.org_id).where(
                    PartnerBrief.token == token
                )
            )
        ).first()
    return (int(row[0]), int(row[1])) if row else None


async def _brief_or_404(token: str, request: Request) -> tuple[int, int]:
    """Budget, then resolve. Raises the same 404 for every kind of miss."""
    ip = client_ip(request)
    if _brief_ip_limited(ip):
        log.warning("Brief rate limit refused a request from %s", ip)
        raise HTTPException(status_code=429, detail="too_many_requests")
    if _brief_global_limited():
        log.error("Global brief ceiling reached — briefs are refused until it clears")
        raise HTTPException(status_code=429, detail="too_many_requests")

    if not _BRIEF_TOKEN.fullmatch(token or ""):
        raise HTTPException(status_code=404, detail="unknown_brief")
    found = await _brief_org(token)
    if found is None:
        # Same body, same status, same timing class as a token that exists but
        # is not yours to have. There is nothing to learn here.
        raise HTTPException(status_code=404, detail="unknown_brief")
    return found


@router.get("/brief/{token}")
async def brief_read(
    token: str, request: Request, db: AsyncSession = Depends(get_db)
) -> dict[str, Any]:
    """The brief itself, plus whatever has been answered so far."""
    brief_id, org_id = await _brief_or_404(token, request)
    set_org_id(org_id)

    brief = await db.get(PartnerBrief, brief_id)
    if brief is None:
        # The row vanished between the two queries. Not reachable in practice;
        # answered like any other miss rather than as a 500, because from the
        # caller's side it is the same fact.
        raise HTTPException(status_code=404, detail="unknown_brief")

    # Stamped once, never refreshed: the question this answers is "have they
    # seen it", and that stops changing the moment it is yes. Overwriting it on
    # every load would turn a fact we use to decide whether to phone somebody
    # into a last-seen timestamp nobody asked for.
    first_open = brief.opened_at is None
    if first_open:
        brief.opened_at = datetime.now(UTC)
        try:
            await db.commit()
        except Exception:  # noqa: BLE001 — reading the page must not depend on it
            await db.rollback()
            log.warning("Could not stamp opened_at on brief %d", brief_id)
            first_open = False

    # After the stamp, and only when the stamp is the one that landed: the
    # doorbell rings for the first open and never again, which is exactly what
    # `opened_at` already means. Ringing it before the commit would announce an
    # open that a rolled-back transaction says never happened.
    if first_open:
        await notify_opened(brief)

    return {
        "title": brief.title,
        "recipient": brief.recipient,
        "payload": brief.payload or {},
        "answers": brief.answers or {},
        "answered_at": brief.answered_at.isoformat() if brief.answered_at else None,
    }


#: How long a typing session goes quiet for before another autosave is worth
#: an email. Sized so a person filling the whole brief in one sitting produces
#: one notice at the start and one when they press the button, rather than one
#: per keystroke-pause.
BRIEF_NOTIFY_QUIET = timedelta(minutes=30)


def _should_notify(deliberate: bool, previous: datetime | None) -> bool:
    """Whether this save is worth telling the operator about.

    The page autosaves about a second after the last keystroke, which is right
    for not losing answers and catastrophic for the inbox: measured in
    production on 13-sep-2026, ninety seconds of typing produced EIGHT emails.
    Notifying on every save was not a bug in the sending, it was a design
    mistake — the notice was written for an event that turned out to happen
    every second and a half.

    So: a deliberate press always tells us, because that is a person saying
    "I am done". An autosave tells us only if the brief has been quiet, so
    somebody who fills it in and never finds the button is still not silent —
    which is the case the notice exists for.
    """
    if deliberate:
        return True
    if previous is None:
        return True
    return datetime.now(UTC) - previous >= BRIEF_NOTIFY_QUIET


@router.post("/brief/{token}")
async def brief_save(
    token: str,
    body: BriefAnswersIn,
    request: Request,
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Replace the answers on this brief.

    Replace, not merge, and that is the safe direction here: the page sends its
    whole state on every save, so a merge would make un-ticking something
    impossible — the cleared key simply would not be in the payload, and the
    old value would survive as a decision nobody made. Concurrent editors are
    not a scenario worth trading that for; there are two readers and they are
    in the same house.
    """
    brief_id, org_id = await _brief_or_404(token, request)

    # Bounded before it is stored, not after. Measured against the serialized
    # form rather than the number of keys: what has to stay small is the row.
    if len(json.dumps(body.answers)) > BRIEF_MAX_ANSWERS:
        raise HTTPException(status_code=413, detail="answers_too_large")

    set_org_id(org_id)
    brief = await db.get(PartnerBrief, brief_id)
    if brief is None:
        raise HTTPException(status_code=404, detail="unknown_brief")

    notify = _should_notify(body.notify, brief.answered_at)
    # Both gates read `answered_at` as it was BEFORE this save overwrites it,
    # and both have to be decided here for that reason. They are not the same
    # question: the email carries the answers, the doorbell carries how far
    # along they are, and only the button means finished.
    ping = should_ping_progress(brief.answered_at)
    brief.answers = body.answers
    brief.answered_at = datetime.now(UTC)
    try:
        await db.commit()
    except Exception:
        await db.rollback()
        log.exception("Could not save answers on brief %d", brief_id)
        raise HTTPException(status_code=500, detail="save_failed") from None

    # After the commit, for the same reason the lead notice is: the answers
    # must be durable before anybody is told about them, and a mail failure
    # must cost the mail, never the save. The page is told it saved either way.
    if notify:
        await send_brief_answered_notice(brief_id)

    # The doorbell, after the letter and after the same commit. "Finished" is
    # the press and nothing else — an autosave that announced somebody had
    # finished would be the one message worth interrupting a day for, sent
    # about a person who is still typing. Otherwise a coalesced checkpoint,
    # and a press is never also a checkpoint: two notices about one save is
    # the flood this module exists to avoid.
    if body.notify:
        await notify_finished(brief)
    elif ping:
        await notify_progress(brief)

    return {"ok": True, "answered_at": brief.answered_at.isoformat()}


# ── Unsubscribe: the switch a commercial email has to carry ──────────────


async def _unsubscribe_target(token: str) -> tuple[int, int] | None:
    """Map a signed token to `(lead id, org id)`, or None.

    The second query in this module that runs outside a tenant, and like
    `_brief_org` it reads two integers and nothing else. The bypass is the same
    justification login has: a stranger arriving with a token has to be resolved
    to an organization BEFORE anything can be scoped to one. The token is signed,
    so this cannot be walked with guessed ids.
    """
    lead_id = lead_id_from_token(token)
    if lead_id is None:
        return None
    async with get_bypass_session_factory()() as meta:
        row = (
            await meta.execute(select(Lead.id, Lead.org_id).where(Lead.id == lead_id))
        ).first()
    return (int(row[0]), int(row[1])) if row else None


def _unsubscribe_page(title: str, body: str, *, form_action: str | None = None) -> HTMLResponse:
    """One self-contained page. No stylesheet, no script, no tracking pixel:
    somebody who is asking us to stop should not be measured on the way out."""
    button = (
        f'<form method="post" action="{form_action}">'
        '<button type="submit">Unsubscribe</button></form>'
        if form_action
        else ""
    )
    return HTMLResponse(
        "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">"
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        '<meta name="robots" content="noindex">'
        f"<title>{title}</title></head>"
        '<body style="font-family:Georgia,serif;max-width:34rem;margin:12vh auto;padding:0 1.5rem;line-height:1.6">'
        f"<h1 style=\"font-weight:400\">{title}</h1><p>{body}</p>{button}</body></html>"
    )


@router.get("/unsubscribe/{token}", response_class=HTMLResponse)
async def unsubscribe_confirm(token: str) -> HTMLResponse:
    """Ask, do not act.

    A GET that unsubscribed on sight would be fired by every link-scanning
    security appliance and spam filter that opens a message before its recipient
    does, and the person would be silently removed from a list they never asked
    to leave. That is why RFC 8058 exists: the POST below is what a mail client's
    own Unsubscribe button sends, so the one-click experience is preserved for
    the reader while a prefetch changes nothing.

    The same page for a token that names nobody. A stranger learns whether a
    signature is valid — which they already knew, having been given it — and
    never whether a lead exists.
    """
    return _unsubscribe_page(
        "Unsubscribe",
        "Confirm and we will stop sending you automated email.",
        form_action=f"/api/v1/public/unsubscribe/{token}",
    )


@router.post("/unsubscribe/{token}", response_class=HTMLResponse)
async def unsubscribe(token: str, db: AsyncSession = Depends(get_db)) -> HTMLResponse:
    """Honour it, and say so.

    Sets `opted_out_at`, which `capture.may_send_automated` reads FIRST for every
    channel — so this silences automated SMS and WhatsApp too, not just email.
    That is deliberate and it is the policy already written into that function:
    "stop means stop", broader than either statute requires. A realtor can still
    write to them personally; nothing automated will.

    The first opt-out wins the date, exactly as the STOP path in
    `conversation.py` has it: the day the agency was first on notice is the
    difference between one violation and thirty, and a second click must not
    reset it.

    Always answers 200 with the same page. A token that names a deleted lead, a
    forged signature and an honest unsubscribe are indistinguishable from
    outside; and a mail client performing RFC 8058 one-click needs a 2xx or it
    tells the reader the unsubscribe failed.
    """
    done = _unsubscribe_page(
        "You are unsubscribed",
        "You will not receive automated email from us again. If you are in the "
        "middle of a conversation with your agent, she can still reply to you "
        "herself.",
    )
    found = await _unsubscribe_target(token)
    if found is None:
        return done
    lead_id, org_id = found
    # Scoped from here on: the bypass above resolved WHICH agency, and the write
    # belongs inside it.
    set_org_id(org_id)
    lead = (await db.execute(select(Lead).where(Lead.id == lead_id))).scalar_one_or_none()
    if lead is None:
        return done
    if lead.opted_out_at is None:
        lead.opted_out_at = datetime.now(UTC)
        lead.opted_out_channel = "email"
        lead.opted_out_keyword = OPT_OUT_KEYWORD
        await db.commit()
        log.info("Lead %d unsubscribed from email", lead_id)
    return done
