export const CURRENT_VERSION = "0.13.0";

export interface VersionEntry {
  version: string;
  date: string;
  title: string;
  changes: string[];
}

export const CHANGELOG: VersionEntry[] = [
  {
    version: "0.13.0",
    date: "2026-05-26",
    title: "Phase 12 — Discovery: búsqueda de leads (4 fuentes) + importar desde cualquier archivo",
    changes: [
      "Nueva pestaña Discovery (como la del sales platform): buscá nuevos leads de negocios en 4 fuentes — Google Maps, Yelp, LinkedIn y Colorado SOS — y sumá una sección para importar tu base de datos existente desde CUALQUIER archivo (PDF, JPG/PNG, TXT, CSV, XLSX, HTML).",
      "Flujo preview-and-select: buscar/subir devuelve resultados transitorios (no se persisten); el dashboard muestra un checklist con select-all y vos elegís cuáles importar → se crean como Leads (status new, meta.source). Dedupe por identificador (teléfono, sino email) contra leads existentes.",
      "services/discovery.py (portado y adaptado del sales platform Eko AI Main, drop de Paperclip): patrón SIMULATED-first como listings.py. Default DISCOVERY_SIMULATED=true → set curado de negocios CO reales-plausibles (sin keys). Adapters reales por fuente: Colorado SOS (Socrata público, GRATIS sin key), Yelp Fusion, Google Maps (Outscraper), LinkedIn (SerpApi) — cada uno degrada a [] sin su key.",
      "services/file_import.py — extracción 'cualquier formato': PDF (pypdf), XLSX (openpyxl), imágenes JPG/PNG vía OCR (pytesseract + tesseract-ocr en el Dockerfile), CSV/TXT/HTML (stdlib + strip de tags). Luego extract_leads pasa el texto por el LLM (json_mode) para sacar contactos como array JSON, con degradación graceful (output malo → [], nunca crashea).",
      "API protegida bajo /api/v1/discovery: POST /search (query/city/state/sources/max_results), POST /upload (multipart, cap FILE_IMPORT_MAX_MB=25), POST /import (crea los leads elegidos). Frontend: /discovery (DiscoveryPanel con 4 chips de fuente + ResultsList reutilizable + FileImport con drag-drop). Link Discovery en el Nav (icono Search).",
      "config + .env.example + compose: DISCOVERY_SIMULATED + YELP_API_KEY/OUTSCRAPER_API_KEY/SERPAPI_API_KEY (se reusan las keys del sales platform) + FILE_IMPORT_MAX_MB. requirements: pypdf/openpyxl/pillow/pytesseract. docs/setup-discovery.md (qué fuente necesita qué key; Colorado SOS gratis; flip DISCOVERY_SIMULATED=false).",
      "Tests +13 (total 145): test_discovery.py (6 — búsqueda simulada devuelve negocios, filtro por fuente, cap max_results, sanitize_email, import crea+dedupe, import sin identificador skip) + test_file_import.py (7 — extract_text plaintext/csv/html-strip/empty, extract_leads parsea JSON array, tolera prosa, output malo→[], texto vacío no llama LLM).",
      "Voz (VAPI/Retell) renumerado a Phase 13.",
    ],
  },
  {
    version: "0.12.0",
    date: "2026-05-26",
    title: "Phase 11 — Hardening para 1er cliente: auth del dashboard + analíticas",
    changes: [
      "Login del dashboard (una oficina = un password compartido): página /login + AuthGuard que redirige si la sesión falta. Token de sesión firmado con HMAC (cookie httpOnly, sin dependencia nueva). Botón de salir en el Nav.",
      "Gate por `AUTH_ENABLED`: el data API (leads/conversations/visits/settings/properties/analytics) requiere login cuando está activo; webhooks + health quedan abiertos. Default OFF (dev + demo público abiertos); el instalador lo activa con un password. WARN al startup si APP_ENV=production y AUTH_ENABLED=false.",
      "Página /analytics: funnel por status, tasa de conversión, leads por canal, por tier de score (🔥/🟡/⚪), tiempo de primera respuesta promedio, y nuevos leads por día (14d). Endpoint GET /api/v1/analytics (solo lectura). Sin librería de charts (barras div).",
      "config + .env.example + compose: AUTH_ENABLED/DASHBOARD_PASSWORD/AUTH_SECRET/AUTH_TTL_HOURS. El instalador (scripts/install.sh) pregunta el password del dashboard y activa auth + genera AUTH_SECRET.",
      "i18n EN/ES para login + analytics; link Analytics en el Nav.",
      "Tests +6 (total 132): auth service (password/token/tamper/expiry) + gate (abierto si disabled, 401/login/cookie si enabled) + envelope de analytics.",
      "Voz (VAPI/Retell) renumerado a Phase 12.",
    ],
  },
  {
    version: "0.11.0",
    date: "2026-05-26",
    title: "Phase 10 — Nurture autónomo + el agente ofrece listings en la conversación",
    changes: [
      "Seguimiento autónomo post-visita: al agendar una visita se encola un recordatorio 24h antes + secuencia post-visita (24h '¿qué te pareció?', 72h nudge si no respondió, 7d 'nuevas similares'). Mensajes bilingües enviados como el agente IA por el canal del lead.",
      "Modelo FollowUp + Alembic 006 (lead/visit/kind/status/scheduled_for, UNIQUE visit+kind → enqueue idempotente). services/followups.py: enqueue_for_visit + process_due_followups (se salta si human_takeover, visita cancelada, o el 72h si el lead ya respondió tras la visita).",
      "Worker in-process (loop asyncio en main.py, FOLLOWUPS_ENABLED + FOLLOWUPS_INTERVAL_SECONDS) que procesa los vencidos; scripts/run_followups.py para cron. El booking de visita encola la secuencia.",
      "El agente ahora OFRECE listings en la conversación: si el lead es buy/rent y tiene zona, el orquestador inyecta los listings emparejados REALES en el system prompt (solo esos, sin inventar) y el LLM los ofrece naturalmente. Cierra el loop de Phase 7 (antes el matching era solo dashboard).",
      "Fix: el matcher coercía mal el presupuesto (float del classifier * Decimal → crash silencioso); normalizado con Decimal(str()). Sin esto la inyección fallaba en vivo.",
      "Tests +6 (total 126): followups (enqueue secuencia + idempotente, past-visit sin reminder, envía vencido, human_takeover skip, cancelada no encola) + agente recibe listings reales en el system prompt.",
      "Voz (VAPI/Retell) renumerado a Phase 11.",
    ],
  },
  {
    version: "0.10.0",
    date: "2026-05-26",
    title: "Dashboard multilingüe (EN default + ES) con selector de idioma",
    changes: [
      "El dashboard ahora es multilingüe: inglés por defecto, español como segunda opción, con un selector de idioma (globo + EN/ES) en el Nav, visible en TODAS las páginas.",
      "lib/i18n.tsx: LanguageProvider client + hook useI18n + diccionarios completos EN/ES. La elección persiste en localStorage y sincroniza <html lang>. t(key) con fallback a EN y a la propia key.",
      "Todos los strings de UI pasan por t(): Nav, páginas (leads/propiedades/settings/detalle), badges (status/intent/score/visit), tabla y detalle de leads, composer, sugerencias, matches, visitas, booking, propiedades, settings, takeover, mensajes.",
      "Formatters locale-aware: relativeTime/exactTime/formatBudget (USD, en/es) + fechas de visitas/booking según el idioma activo.",
      "PageHeader client para los títulos; la página de detalle de lead es client. Landing /about con copy refrescado (MLS matching).",
      "Default English alineado con el pivote USA; el agente backend ya respondía en el idioma del lead (Phase 3) — esto hace bilingüe también la interfaz del realtor.",
    ],
  },
  {
    version: "0.9.1",
    date: "2026-05-26",
    title: "SMS hardening — A2P MessagingServiceSid + delivery status callbacks",
    changes: [
      "Tras leer la doc oficial de Twilio, dos mejoras de producción del canal SMS: (1) envío vía MessagingServiceSid para A2P 10DLC, (2) tracking de entrega real vía StatusCallback.",
      "send_sms: si TWILIO_MESSAGING_SERVICE_SID está seteado, envía con MessagingServiceSid (usa la campaña/pool A2P registrado) en vez del From crudo — recomendado por Twilio para entrega US. Fallback a TWILIO_PHONE_NUMBER.",
      "StatusCallback: nuevo endpoint POST /api/v1/webhooks/sms/status. Si TWILIO_STATUS_CALLBACK_URL está seteado, send_sms pide a Twilio que postee actualizaciones (sent→delivered/undelivered/failed + ErrorCode). El backend refleja el estado final en el Message → el dashboard muestra entrega real (y loguea errores de carrier como 30034 = A2P sin registrar). Mapper twilio_status_to_delivery.",
      "config.py + .env.example + compose: TWILIO_MESSAGING_SERVICE_SID + TWILIO_STATUS_CALLBACK_URL.",
      "docs/setup-twilio.md ampliado: registro A2P 10DLC (Sole Proprietor vs Standard), gotcha del webhook del Messaging Service (anula el del número), y opt-out STOP/HELP (Twilio lo maneja por default).",
      "Webhook inbound: log de fallo de firma más limpio (sin el diagnóstico verbose temporal).",
      "Tests +4 (total 120): mapper de estado (1) + status callback e2e (delivered, undelivered/30034→failed, sid desconocido = no-op).",
    ],
  },
  {
    version: "0.9.0",
    date: "2026-05-26",
    title: "Phase 9 — Canal SMS (Twilio)",
    changes: [
      "Tercer canal: SMS vía Twilio Programmable Messaging, sobre la misma arquitectura multicanal de Phase 3 (ParsedMessage + dispatcher + channel='sms'). El agente captura, clasifica, scorea y responde igual que WhatsApp/Email.",
      "services/sms.py: send_sms (SIMULATED loguea / real POST a la REST API de Twilio con basic auth), verify_twilio_signature (HMAC-SHA1 sobre URL + params POST ordenados, keyed por el auth token), parse_inbound_sms(form)->ParsedMessage.",
      "Webhook POST /api/v1/webhooks/sms: parsea el form de Twilio, valida X-Twilio-Signature (salvo SIMULATED), delega al orquestador, responde TwiML vacío (la respuesta sale async vía REST). La URL para la firma es TWILIO_WEBHOOK_URL o se reconstruye de los forwarded headers (proxy/tunnel).",
      "Idempotencia vía UNIQUE messages.external_id (MessageSid) — los reintentos de Twilio no duplican.",
      "config.py + .env.example + compose: SMS_SIMULATED (default true), TWILIO_ACCOUNT_SID/AUTH_TOKEN/PHONE_NUMBER/WEBHOOK_URL. scripts/simulate_inbound_sms.py para smoke testing.",
      "docs/setup-twilio.md: cuenta + número + webhook + firma + notas de costo/seguridad.",
      "Tests +9 (total 116): test_sms_service.py (7 — firma válida/tampered/wrong-token/missing, parse ok/missing, send simulated) + test_sms_webhook_e2e.py (2 — inbound crea lead+conversation channel=sms, idempotencia en reintento).",
      "Voz (VAPI/Retell) sigue diferida como Phase 10 hasta tener cuenta de proveedor.",
    ],
  },
  {
    version: "0.8.0",
    date: "2026-05-26",
    title: "Phase 8 — Lead intelligence (scoring + priorización + digest)",
    changes: [
      "Lead scoring 0-100 determinista y explicable: services/scoring.py puntúa señales que el pipeline ya produjo (intent LLM + entidades extraídas + engagement + recency + visita) SIN llamadas LLM extra por lead, así la lista rankea rápido y barato. Componentes: intent 20 · budget 15 · engagement 15 · urgency 12 · zone 10 · recency 10 · visit 10 · property_type 8. Status gate: WON/LOST→0, PAUSED→mitad.",
      "Columnas leads.score (Int indexado) + score_breakdown (JSON con desglose por componente + tier). Alembic 005. El orquestador recomputa el score tras cada turno inbound; POST /leads/rescore-all para backfill.",
      "Tiers 🔥 hot (≥67) / 🟡 warm (≥34) / ⚪ cold. ScoreBadge en cada fila de la tabla de leads; la lista ahora ordena por score por defecto (sort=score|recent).",
      "GET /leads/digest — top leads calientes/activos (excluye won/lost/paused, score>0) → panel 'Leads calientes — a quién llamar primero' arriba de /leads. scripts/daily_digest.py para cron (imprime el digest, pipe-able a email/Telegram).",
      "Lead detail muestra el ScoreBadge con label en el header. score + score_breakdown expuestos en LeadOut.",
      "Tests +11 (total 107): test_scoring.py (8 — lead vacío 0, fully-qualified=100 hot, won/lost zeroed, paused halved, engagement escala, recency decae, clamp 0-100, umbrales de tier) + test_lead_digest.py (3 — rescore+digest rankea y excluye cerrados, list default sort=score, LeadOut tiene score).",
      "Sin cuentas externas. SMS (Twilio) renumerado a Phase 9, Voz (VAPI/Retell) a Phase 10 — siguen diferidas hasta tener cuentas.",
    ],
  },
  {
    version: "0.7.0",
    date: "2026-05-25",
    title: "Phase 7 — MLS/IDX listings (RESO) + per-lead property matching",
    changes: [
      "Property model reworked para USA: source enum reso/idx/mls/manual + status enum (active/pending/sold/off_market), bedrooms/bathrooms (half-baths 2.5)/sqft/property_type/address/city/state/zip/zone/lat-lng/photos/description/listed_at. Alembic 004 dropea+recrea la tabla placeholder EU (estaba vacía).",
      "services/listings.py: fetch_listings (SIMULATED = set curado de 9 listings Miami / real = RESO Web API OData con RESO_BASE_URL+RESO_ACCESS_TOKEN), sync_listings (upsert idempotente por source+external_id), match_properties_for_lead (gate de intención rent/sale + zona + presupuesto ±10% + tipo).",
      "Endpoints: GET /properties (filtros status/source/city/zone/type/min-max price + paginado), POST /properties/sync (ingest), GET /properties/{id}, GET /leads/{id}/matches (listings que encajan con el lead).",
      "Frontend: página /properties con grid de PropertyCard + filtros zona/precio + botón 'Sincronizar MLS'. MatchesSection en el detalle del lead muestra 'Propiedades sugeridas' con botón 'Enviar al lead' (manda blurb formateado vía composer). Link 'Propiedades' en el Nav.",
      "Listings SIMULATED por default (LISTINGS_SIMULATED=true) — el dashboard + matching funcionan sin cuenta MLS; producción vía docs/setup-mls.md. Las zonas del set demo coinciden con los leads demo (Brickell/Coral Gables/Doral/Wynwood/Edgewater/Little Havana).",
      "scripts/sync_listings.py ingest CLI (idempotente, cron-friendly). config.py + .env.example + docker-compose env (LISTINGS_SIMULATED/PROVIDER/RESO_*).",
      "Tests +12 (total 96): test_listings_service.py (5 — fetch simulado, sale+rent, filtro ciudad, ciudad inexistente vacía, limit) + test_properties_api.py (7 — sync idempotente, list+filtros, filtro precio, get 404, matches 404, buy-lead Brickell sale-only, rent-lead solo rentals).",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-05-25",
    title: "Phase 6 — Single-customer installer + branding panel + public demo",
    changes: [
      "Settings API: GET/PUT /api/v1/settings sobre el singleton AgentSettings (auto-creado con defaults). PUT hace partial update con normalización/dedupe de languages (lowercase, sin vacíos). Cada oficina puede brandear su propia instancia.",
      "Frontend /settings — panel de branding: nombre + teléfono de la agencia, persona del agente (system prompt), saludo, idiomas (chips es/en/pt/fr), horario de atención (por día, open/close o cerrado). Link 'Configuración' en el Nav. Cambios aplican de inmediato a las respuestas.",
      "scripts/install.sh — instalador single-customer interactivo: chequea prereqs (docker/compose/daemon), genera .env con secretos aleatorios fuertes (POSTGRES_PASSWORD, WHATSAPP_VERIFY_TOKEN) mode 600 nunca impresos, build+up, espera health, alembic upgrade head, fija branding vía API. Canales quedan SIMULATED salvo opt-in explícito. --no-prompt para provisioning.",
      "backend/scripts/seed_demo.py — dataset demo idempotente (Sunset Realty Group, Miami): 6 leads bilingües EN/ES + conversaciones realistas + 2 visitas (scheduled/completed). Marca meta.demo=true; --reset borra solo filas demo; --keep-settings preserva branding. Para que inmo-demo.ekoaiautomation.com luzca vivo.",
      "deploy/cloudflared/config.example.yml + docs/setup-demo.md — tunnel DEDICADO para inmo-demo.ekoaiautomation.com (aislado del tunnel eko-landing de la sales platform). Modelo de seguridad: todos los canales SIMULATED (un visitante nunca dispara un envío real), datos seed (sin PII real), opcional Cloudflare Access.",
      "docs/install.md — guía completa de instalación single-office + enable de canales (WhatsApp/Resend/Cal.com) + upgrade. Sin GPU (LLM en la nube Kimi+MiniMax).",
      "CI verde por primera vez desde Phase 1: backend agrega servicio Postgres + alembic upgrade head (los tests con DB ahora corren de verdad) + ruff config ignora 3 reglas que chocan con idioms intencionales (B008 FastAPI Depends, UP042 str-Enum, UP037 SQLAlchemy forward-refs) + auto-fix del resto. Frontend quita cache npm (no había package-lock.json → abortaba el job).",
      "Tests +7 (total 84): test_settings_api.py (GET auto-create defaults, PUT update + persiste, partial update no toca otros campos, languages normalize/dedupe, body vacío 400, campo desconocido 422, languages vacío 422). test_models singleton hecho robusto (no acopla agency_name a un valor fijo).",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-05-25",
    title: "Phase 5 — Calendar booking (Cal.com) con SIMULATED + dashboard VisitsSection",
    changes: [
      "Visit model (id, lead_id FK CASCADE, calendar_provider, external_booking_id UNIQUE, status enum scheduled/confirmed/cancelled/completed/no_show, scheduled_at indexed, duration_minutes, timezone, property_address, meeting_url, notes, timestamps). Alembic migration 003_phase5_visits.",
      "services/calendar_cal.py — Cal.com v2 API wrapper: list_available_slots, create_booking, cancel_booking. SIMULATED mode genera slots weekday 10/11/14/15/16 in-memory + IDs calcom-sim-<uuid>; producción hace HTTP a api.cal.com con cal-api-version 2024-08-13 header.",
      "4 endpoints nuevos: GET /leads/{id}/calendar/slots?days=N&timezone=, POST /leads/{id}/calendar/book, GET /leads/{id}/visits, POST /visits/{id}/cancel. Slots filtra busy_starts del lead (no double-booking en la misma conversación).",
      "Auto-pick email vs phone para attendee: si lead.phone contiene '@' → email para Cal.com; sino phone. Lead sin email + producción real → 503 con mensaje claro.",
      "Frontend: VisitsSection en LeadDetail muestra upcoming + past visits con cards (VisitStatusBadge, fecha localizada ES, dirección, notas, cancel button). BookingDialog modal con date-grouped slot picker, dirección opcional, notas, confirm.",
      "Dashboard URLs: /leads/{id} ahora muestra (top→bottom): Header con metadata + TakeoverToggle (Phase 2), Conversación chat (Phase 1-3), Composer + Sugerir (Phase 4), VisitsSection + Agendar visita (Phase 5).",
      "Tests +13 (total 77): test_calendar_service.py (7 — weekday-only, hours match, busy filter, simulated mode, booking sim id, cancel sim, calcom-sim-* always-local-cancel) + test_visits_api.py (6 — slots endpoint, slots 404, book creates Visit, list visits, cancel flips + rejects re-cancel, no double-booking).",
      "docs/setup-calcom.md producción walkthrough (Cal.com account + event type + API key + DNS-less). CALENDAR_SIMULATED env var (default true) + CALCOM_BASE_URL (default api.cal.com).",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-05-25",
    title: "Phase 4 — Composer manual + AI reply suggestions (completa el loop de takeover)",
    changes: [
      "Composer box en /leads/[id]: el realtor escribe una respuesta y la envía vía el canal del lead (WhatsApp/Email). Se persiste como Message(sender=HUMAN, direction=OUTBOUND) y se rutea por el dispatcher multichannel existente.",
      "Botón 'Sugerir respuestas': genera 3 borradores de respuesta vía LLM (Kimi/MiniMax). Cada sugerencia es clickeable y llena el textarea del composer — el realtor puede editarla antes de enviar.",
      "Backend nuevo: POST /api/v1/leads/{id}/messages (human send con auto-pick del canal de la última conversación activa; threading email via In-Reply-To del último inbound) + POST /api/v1/leads/{id}/suggestions (genera N respuestas en formato JSON array, degrada a [] + error en caso de LLM fail o JSON inválido).",
      "Orchestrator: 2 funciones nuevas — send_human_message + generate_reply_suggestions. Usan el dispatcher existente, la detección de idioma del Phase 3, y AgentSettings.languages.",
      "Auto-pick canal: si el lead tiene múltiples conversaciones activas (multichannel), el composer usa la última activa. Para email auto-prepende 'Re:' + In-Reply-To header.",
      "UX: 'count' clampado a [1, 5]. Composer muestra contador 0/4000 chars. Errores in-line (no toast/modal). router.refresh() tras send → nueva burbuja aparece en el chat sin recargar.",
      "Tests +8: human-send happy path (WhatsApp simulated routing), lead-not-found error, empty text 400, lead-without-conversation error, suggestions happy path, suggestions con prose alrededor del JSON, suggestions LLM fail degrade graceful, suggestions count clamp 99→5.",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-05-25",
    title: "Phase 3 — Multichannel + Email (Resend) + Bilingual (USA pivot)",
    changes: [
      "Pivote estratégico USA: el target de clientes pasa de inmobiliarias EU (WhatsApp-first) a realtors USA donde dominan SMS, Email y llamadas. WhatsApp queda como canal opcional para clientes internacionales.",
      "Multichannel refactor: schema agnóstico al canal. Renames messages.wa_message_id→external_id, wa_status→delivery_status, conversations.wa_thread_id→external_thread_id. + messages.subject (email). leads.phone widened 32→254 chars (acepta emails como identifier). Alembic migration 002_phase3_multichannel preserva rows existentes.",
      "ParsedMessage común en services/_common.py — dataclass con channel, external_id, from_identifier, content, subject, thread_id. Cada canal (WhatsApp / Email / SMS / Voice) emite el mismo tipo.",
      "Orchestrator con dispatcher: handle_inbound_message ahora rutea outbound a whatsapp_send / email_send según conversation.channel. Lazy imports — un deploy puede no tener Resend SDK si no usa email.",
      "Email channel (Resend): services/email.py con send_email (threading via In-Reply-To + References), parse_inbound_email (Resend payload + HTML fallback), verify_resend_signature (Svix-style HMAC con multi-sig support). EMAIL_SIMULATED=true en dev (loguea outbound, no requiere cuenta Resend ni DNS).",
      "Webhook nuevo: POST /api/v1/webhooks/email — mismo contrato que WhatsApp (200 + UNIQUE external_id catches retries).",
      "Bilingüe: services/i18n.py con detect_language (langdetect, seed determinista) + pick_supported_language (whitelist AgentSettings.languages) + language_instruction (steering line ES/EN para el system prompt). Detecta del último inbound, NO bias en réplicas históricas del agente. Classifier acepta language_hint opcional.",
      "Dashboard: MessageBubble muestra channel icon (envelope email, message-circle WhatsApp, message-square SMS, phone voice) + asunto del email visible cuando applies. LeadsTable muestra heuristic-based glyph al lado del identificador (email vs phone).",
      "Backend: PATCH lead endpoint Phase 2 sigue funcionando. Pydantic schemas en conversations.py actualizados al naming nuevo (external_id / delivery_status / subject / external_thread_id).",
      "Tests: 55 total (45 + 10 nuevos = 8 email service + 9 i18n - 7 duplicados/colectados). E2E email crea Lead via address, Conversation(channel=email), 2 Messages con subject + threading.",
      "Frontend lib/api.ts: Message + Conversation interfaces alineadas al backend nuevo (external_id, delivery_status, subject, external_thread_id).",
      "Roadmap reordenado post-pivote USA: Phase 4=SMS (Twilio), Phase 5=Voice (VAPI/Retell), Phase 6=Calendar (movido desde Phase 3), Phase 7=MLS/IDX (USA equivalente Idealista), Phase 8=installer + demo subdomain.",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-05-25",
    title: "Phase 2 — Realtor dashboard (lista leads + chat view + human takeover)",
    changes: [
      "Dashboard frontend funcional en Next.js 14 App Router. Reemplaza el landing placeholder en `/` (que ahora redirige a `/leads`). La landing vieja queda accesible en `/about`.",
      "`/leads` — tabla de leads con filtros por status (Nuevo/Cualificado/Visitando/Post-visita/Cerrado/Perdido/Pausado) e intent (Alquiler/Compra/Tasación/Otro). Click en un lead → vista detalle.",
      "`/leads/[id]` — vista detalle con metadata del lead (nombre, teléfono, zona, presupuesto, tipo, urgencia, timestamps) + conversación completa estilo chat (burbujas inbound/outbound, indicador de provider LLM, status de envío Meta) + toggle de control humano.",
      "Toggle 'Humano vs IA' — botón que llama `PATCH /api/v1/leads/{id}` con `{human_takeover: true|false}`. Cuando está ON, el orchestrator NO genera respuesta automática para el siguiente mensaje entrante (Phase 1 ya respeta esta flag).",
      "Componentes: `Nav` (top bar con branding + links), `StatusBadge` + `IntentBadge` (paleta por categoría), `FilterBar` (querystring-based, Suspense para SSR), `LeadsTable` (lista con virtualización ligera), `MessageBubble` (chat-style con sender icons), `LeadDetail`, `TakeoverToggle`.",
      "API client tipado en `lib/api.ts` — interfaces TypeScript para Lead, Conversation, Message + funciones `leadsApi.list/get/patch` y `conversationsApi.get`. Helper `format.ts` con tiempos relativos en castellano + formato de presupuesto.",
      "Backend: nuevo endpoint `PATCH /api/v1/leads/{id}` con schema `LeadPatch` (partial update, `extra='forbid'` rechaza campos desconocidos con 422). Acepta name, status, intent, zone, budget_min/max, property_type, urgency, human_takeover.",
      "`next.config.js` proxya `/api/*` a `INTERNAL_API_URL` (default `http://backend:8000`) — cliente JS siempre habla same-origin, funciona desde LAN/Tailscale/futuro Cloudflare sin reconfigurar URLs.",
      "Tests +8: `test_leads_api.py` cubre list envelope, get 404, PATCH takeover toggle, PATCH partial update (status+zone sin tocar name), PATCH body vacío 400, PATCH campo desconocido 422, PATCH status inválido 422, PATCH 404. Total ahora: 33 tests.",
      "Brand rename completo Inmobiliario → Realtors en `<title>`, landing copy, README.",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-05-25",
    title: "Phase 1 CORE — WhatsApp 24/7 agent with Kimi + MiniMax fallback",
    changes: [
      "Identity setup: CLAUDE.md raíz con anti-patterns + port map + 3-líneas-de-trabajo distinction; GitHub topics + 5 milestones; CI workflow (ruff + pytest + tsc + lint).",
      "Port remap: container stack `eko-realestate-*` en 3004/8011/5434/6381 para coexistir con la sales platform prod (3001/8000/5432/6379), su main dev paralela (3003/8010/5433/6380) y el preview pricing-v2 (3002). Cero colisión.",
      "DB layer: SQLAlchemy 2.x async + Alembic baseline migration. 5 modelos: Lead (con status/intent enums, budget, zone, urgency, human_takeover), Conversation, Message (UNIQUE wa_message_id para idempotencia de webhooks), Property (placeholder Phase 4), AgentSettings (singleton con persona en castellano + business_hours).",
      "LLM client: Kimi 2.6 primary + MiniMax M2.7 fallback. Fallback INLINE por request (si Kimi timeout/429/5xx, mismo request reintenta con MiniMax antes de fallar). Ambos via SDK `anthropic` con `base_url` distinto. A/B test script con 5 prompts ES típicos validó calidad real (Kimi ~3.4s avg, MiniMax ~5.6s; ambos producen castellano natural).",
      "Intent classifier: clasifica rent/buy/valuation/other + extrae zona, presupuesto, tipo, urgencia. Pydantic schema valida; degrada a OTHER + log raw_response cuando JSON inválido. Coerce \"1.500€\" → 1500.0.",
      "WhatsApp webhook: GET handshake verify (token + challenge), POST inbound con HMAC-SHA256 verify (`X-Hub-Signature-256`). Modo SIMULATED por default (loguea outbound en vez de POST a Meta) — desarrollo sin Meta Business App. Warning al startup si SIMULATED=true Y APP_ENV=production.",
      "Conversation orchestrator: inbound → upsert Lead → save inbound Message → classify intent (aplica si confidence ≥ 0.55) → genera reply con LLM → save outbound Message (status=PENDING) → send via WhatsApp Cloud API → update wa_message_id + status (SENT/FAILED). Idempotencia via UNIQUE wa_message_id (Meta retries no duplican leads).",
      "API routes: `GET /api/v1/leads` (lista paginada con filtros status/intent), `GET /api/v1/leads/{id}` (detail), `GET /api/v1/conversations/{lead_id}` (full history).",
      "Tests: 23 total — 4 LLM fallback (mocked anthropic SDK), 7 classifier (mocked LLM responses), 7 signature (HMAC valid/invalid/missing/tampered/wrong-secret), 2 webhook E2E (full flow + idempotency), 2 models (roundtrip + AgentSettings), 1 health. Live DB required for E2E + models.",
      "Script `simulate_inbound.py` para CLI testing manual: `python scripts/simulate_inbound.py \"+34666123456\" \"Hola...\"` → POST simulado al webhook.",
      "Doc `setup-whatsapp.md` con flow completo Meta App → secrets → webhook registration → production checklist + troubleshooting.",
    ],
  },
  {
    version: "0.0.1",
    date: "2026-05-25",
    title: "Bootstrap",
    changes: [
      "Repo skeleton: FastAPI backend + Next.js frontend + Postgres + Redis + Ollama via docker-compose.",
      "Health endpoint at GET /api/v1/health.",
      "Landing placeholder with brand-aligned design (Eko AI violet palette).",
      "README + roadmap + architecture docs.",
    ],
  },
];
