export const CURRENT_VERSION = "0.29.1";

export interface VersionEntry {
  version: string;
  date: string;
  title: string;
  changes: string[];
}

export const CHANGELOG: VersionEntry[] = [
  {
    version: "0.29.1",
    date: "2026-06-02",
    title: "Lead inexistente: estado 'no encontrado' amigable (no más error rojo crudo)",
    changes: [
      "Abrir un lead que ya no existe (ej. un link viejo a una ficha que se fusionó o se borró) mostraba un cuadro rojo crudo 'API 404: Lead not found'. Ahora muestra un estado limpio 'Lead no encontrado' con la pista de que pudo fusionarse/eliminarse y un botón para volver a la lista de leads.",
    ],
  },
  {
    version: "0.29.0",
    date: "2026-06-02",
    title: "Inbox: contador 'nuevo + pendiente' y menú desplegable de acceso rápido",
    changes: [
      "El número del Inbox en el nav ahora cuenta también las comunicaciones NUEVAS sin revisar (ej. una llamada de voz recién terminada), no solo las que esperan tu respuesta. Así una llamada nueva se refleja al instante.",
      "Clic en el Inbox abre un menú: arriba 'Ir a la bandeja' (sección general) y debajo acceso directo a cada comunicación nueva/pendiente (con su ícono de canal 🗣️✉️💬 y vista previa) que lleva directo a la ficha del lead.",
      "Abrir un lead lo marca como revisado y lo saca del contador — salvo que todavía esté esperando tu respuesta (ese se limpia al responder o con 'Atendido').",
      "Backend: nuevo `needs_attention` (= esperando respuesta O actividad nueva sin atender en las últimas 24h) + filtro `attention` en `GET /inbox` y campo `attention` en el contador.",
    ],
  },
  {
    version: "0.28.1",
    date: "2026-06-02",
    title: "Fix voz: la llamada queda en UNA sola ficha (transcript + visita + datos)",
    changes: [
      "Bug: una llamada se partía en dos leads — la VISITA caía en el número que el cliente dictaba y la TRANSCRIPCIÓN en el caller id real. Fix: `book_visit` ahora ancla el lead al caller id (el mismo que usa el ingest del end-of-call), y guarda el número dictado como nota de callback. Así visita y transcripción quedan en la misma ficha.",
      "Bug: VAPI devolvía el `structuredData` en un shape anidado (`customer_info`/`property_inquiry`) que no se mapeaba → el lead quedaba sin intención/zona/presupuesto. Fix: `_flatten_voice_structured` normaliza el shape plano Y el anidado; además se define un schema EXPLÍCITO en el assistant para que las llamadas futuras vengan deterministas.",
    ],
  },
  {
    version: "0.28.0",
    date: "2026-06-02",
    title: "Phase 13 · Agente de voz (VAPI) — llamadas que cualifican y agendan visitas",
    changes: [
      "Nuevo canal de VOZ: el agente atiende llamadas vía VAPI (voz femenina en inglés 11labs + Claude Sonnet 4.5 como cerebro en tiempo real). Cualifica al cliente (compra/renta/tasación, zona, presupuesto, timeline) y puede AGENDAR UNA VISITA durante la misma llamada.",
      "Al colgar, la llamada se ingiere al timeline del lead (channel=\"voice\") con la transcripción completa, los campos extraídos y el score recalculado — igual que SMS/email. Aparece en `/leads/{id}` con las burbujas de voz 🗣️.",
      "Backend: `services/voice.py` (verificación del secret de VAPI, parseo del end-of-call-report, tool-calls `check_availability`/`book_visit` que reutilizan Cal.com de Phase 5) + `POST /api/v1/webhooks/voice` (responde los tool-calls en vivo y, sin LLM, ingiere la llamada terminada). Idempotente por call_id.",
      "`VOICE_SIMULATED=true` por defecto (dev + demo no necesitan cuenta VAPI). Outbound (que el agente LLAME a leads) queda para una fase futura. Doc: `docs/setup-vapi.md`.",
    ],
  },
  {
    version: "0.27.1",
    date: "2026-06-01",
    title: "Threading de email más robusto: References con la cadena completa del hilo",
    changes: [
      "Refuerzo del threading: la respuesta del agente ahora setea el header `References` con la CADENA COMPLETA (raíz del hilo … mensaje del lead), no solo el `In-Reply-To` al padre. Esto hace que Gmail/Outlook aniden la respuesta dentro de la conversación de forma confiable en vez de abrir un hilo nuevo.",
      "`services/email.py::send_email` acepta `references`; `conversation.py` arma la cadena desde `thread_id` (raíz) + `external_id` (mensaje entrante) y la pasa al envío.",
    ],
  },
  {
    version: "0.27.0",
    date: "2026-06-01",
    title: "Inbound email: traer cuerpo + Message-ID reales (Received Emails API) → threading correcto",
    changes: [
      "Causa del 'responde con correo nuevo en vez de enganchar al hilo': el webhook `email.received` de Resend es SOLO-METADATA (sin cuerpo ni headers), así que el inbound entraba con contenido vacío y sin el Message-ID real → la respuesta no podía threadearse.",
      "Fix: el handler del webhook ahora hace `GET /emails/inbound/{id}` (Received Emails API) para traer el correo COMPLETO — `text`, `message_id` RFC822 y `references`/`in_reply_to` — y se lo pasa al orquestador. Así el agente lee el mensaje real y la respuesta sale con `In-Reply-To`/`References` correctos → Gmail la engancha al hilo.",
      "`services/email.py`: nuevo `fetch_inbound_email(id)` + `_strip_quoted_reply()` (quita el historial citado tipo 'On … wrote:' / '>' para que el agente vea solo el mensaje nuevo). El path SIMULADO (tests) no hace fetch (ya trae el cuerpo).",
      "Nota: la entrega externa (Gmail→Resend) SÍ funcionaba — los correos estaban en la Received Emails API; lo que faltaba era traer su contenido al backend.",
    ],
  },
  {
    version: "0.26.1",
    date: "2026-06-01",
    title: "Guard anti-loop de email: el agente nunca se responde a sí mismo",
    changes: [
      "Fix de seguridad: un email entrante cuyo remitente es NUESTRA propia dirección de envío (`noreply@<dominio>`) ahora se ignora. Sin esto, una respuesta/bounce dirigida a noreply@ volvía a entrar por el webhook inbound y el agente se respondía a sí mismo en un loop infinito (gastando LLM + enviando emails). Detectado en pruebas de inbound.",
      "`services/conversation.py`: guard al inicio de `handle_inbound_message` — si `channel=email` y el remitente == la dirección de `RESEND_FROM`, retorna `ignored_self_loop` sin crear lead ni responder. +1 test.",
    ],
  },
  {
    version: "0.26.0",
    date: "2026-06-01",
    title: "Idioma del agente: inglés por defecto, espejando el idioma del lead (o el que pida)",
    changes: [
      "Las comunicaciones del agente ahora son en INGLÉS por defecto. Si el lead escribe en otro idioma soportado (es/en) se le responde en ese idioma (mirroring), y si pide explícitamente otro idioma, el agente cambia a ese.",
      "`services/i18n.py`: `DEFAULT_LANGUAGE` pasó de `es` a `en` (default cuando no se detecta idioma / texto ambiguo). La línea de steering ahora permite override explícito ('UNLESS the client asks for another language' / 'SALVO que pida otro idioma').",
      "`services/conversation.py`: el orden de idiomas soportados por defecto pasó a `['en','es']` (en el reply y en las sugerencias) → un idioma no soportado cae a inglés. Antes el default era español.",
      "Tests i18n: +3 (default inglés, mirroring con orden en-first, override por solicitud explícita).",
    ],
  },
  {
    version: "0.25.0",
    date: "2026-06-01",
    title: "Fallback LLM local con Gemma (Google) vía Ollama — el agente responde aunque las cuotas de pago estén agotadas",
    changes: [
      "Causa detectada: el agente dejó de responder a los leads porque los DOS proveedores LLM de pago quedaron sin cuota (Kimi: 'usage limit for this billing cycle'; MiniMax: 'usage limit exceeded'). No era el email ni el código.",
      "Solución: se agregó un tercer proveedor LLM — Gemma (modelo open de Google) corriendo LOCAL en Ollama en el ROG — como fallback final gratuito. Orden: Kimi → MiniMax → Gemma local. Los de pago siguen primero por calidad; cuando ambos fallan, Gemma local garantiza que el lead reciba respuesta sin costo ni cuota.",
      "`services/llm.py`: nuevo provider `ollama` que habla la API nativa de Ollama (`/api/chat`, con `format=json` para el clasificador), separado del protocolo Anthropic de Kimi/MiniMax. Se activa con `OLLAMA_ENABLED=true`. +1 test.",
      "Config: `OLLAMA_ENABLED`/`OLLAMA_BASE_URL`/`OLLAMA_MODEL`/`OLLAMA_TIMEOUT_SECONDS` en config.py + docker-compose. En el ROG el demo usa `gemma3:4b` (entra en la RTX 3070 8GB).",
    ],
  },
  {
    version: "0.24.1",
    date: "2026-05-31",
    title: "Fix Add Lead: presupuesto acepta '600k'/'1.2M' y errores de validación legibles",
    changes: [
      "Bug: en Add Lead, escribir el presupuesto como '600k'/'800k' mandaba el string crudo al backend → 422 'Input should be a valid decimal', y el error se mostraba como JSON crudo en el modal.",
      "Fix: el presupuesto ahora se normaliza en el cliente — acepta '600k', '1.2M', '600,000', '$850000' y los convierte a número antes de enviar (k=×1.000, M=×1.000.000). Si queda algo no numérico, muestra un aviso claro en vez de mandar basura al backend.",
      "Fix: `errorDetail` (lib/api.ts) ahora formatea los errores de validación de FastAPI (cuando `detail` es un array) como texto legible 'campo: mensaje' en vez de volcar el JSON crudo (que además podía romper React si se renderizaba como objeto).",
    ],
  },
  {
    version: "0.24.0",
    date: "2026-05-31",
    title: "Capa de potencia en Properties (buscador + chips de tipo + orden) y Analytics (tendencia semanal)",
    changes: [
      "Continúa el diseño de escritorio de Claude Design: misma capa 'intuitivo pero potente' ahora en Properties y Analytics. Solo frontend, sin cambios de backend.",
      "Properties = explorador estilo CRM: buscador en vivo (zona/dirección/título/tipo) con atajo `/`, chips de filtro por tipo de propiedad (derivados de los listings cargados), filtro de precio máximo, orden conmutable Recientes↔Precio, contador 'N de M activas', estado vacío con limpiar. Se mantiene el botón Sincronizar MLS.",
      "Analytics: indicadores de tendencia ▲/▼ calculados de verdad desde `leads_per_day` — nueva tarjeta 'Nuevos esta semana' (suma de los últimos 7 días) con delta % vs. los 7 días previos, y la gráfica por día resalta la semana actual (barras vivas) vs la anterior (atenuadas). Sin métricas inventadas: la tendencia solo se muestra donde hay serie temporal real.",
      "i18n EN+ES para todo lo nuevo. Todo responsive; no toca móvil ni el resto del dashboard.",
    ],
  },
  {
    version: "0.23.0",
    date: "2026-05-29",
    title: "Escritorio más potente: Leads tipo CRM (buscador + filtros + orden) y detalle con acciones rápidas + 'Why this score'",
    changes: [
      "Implementa el diseño de escritorio de Claude Design: que el realtor sienta el sistema intuitivo pero potente. (El móvil quedó en v0.22.0; esto es la capa de escritorio.)",
      "Leads ahora es un explorador tipo CRM (`LeadsExplorer`, reemplaza FilterBar+LeadsTable): buscador en vivo (nombre/zona/contacto/intención/tipo) con atajo de teclado `/`, chips de filtro inteligentes (Todos · 🔥 Hot · Por responder · New · Qualified · Visiting · Won), orden conmutable Prioridad↔Reciente (server-side vía sort) con contador 'N de M', filas más ricas (barra de acento rojo→ámbar en hot, punto ámbar de 'por responder', chevron al hover) y estado vacío con limpiar filtros.",
      "Backend: `GET /leads` ahora devuelve `needs_response` por lead (último mensaje entrante = espera respuesta), con una query agrupada scoped a la página (sin N+1, mismo patrón que el buzón). Alimenta el chip 'Por responder' y el punto de la fila. +1 test.",
      "Detalle del lead: barra de acciones rápidas (Responder → enfoca el composer · Llamar → tel: en leads con teléfono · Agendar visita → scroll a visitas · Marcar ganado → PATCH status=won) + tarjeta 'Why this score' que visualiza el `score_breakdown` real (Intención/Presupuesto/Interacción/Urgencia/Zona/Tipo/Recencia/Visita) con barras degradadas.",
      "Pulido global: anillo de foco accesible (`:focus-visible`) + scrollbar oscuro a juego con el noir.",
      "i18n EN+ES para todo lo nuevo. El escritorio gana potencia sin romper la versión móvil (todo responsive).",
    ],
  },
  {
    version: "0.22.1",
    date: "2026-05-29",
    title: "Fix: 'Sign in with Google' funciona en móvil (popup → redirect)",
    changes: [
      "Bug: en el teléfono, tocar 'Sign in with Google' abría una pestaña nueva en `accounts.google.com/gsi/transform` que quedaba EN BLANCO y no dejaba continuar. Causa: el botón usaba el modo popup por defecto; los navegadores móviles abren el popup como pestaña separada y el credencial nunca vuelve a la pestaña original. (En desktop el popup sí funcionaba.) No lo causó la release móvil v0.22.0 — la config de Google estaba correcta.",
      "Fix: el botón ahora usa `ux_mode=redirect` + `login_uri` → Google hace una navegación de página completa (sin popups) y postea el ID token al backend. Funciona igual en móvil y desktop.",
      "Backend: nuevo `POST /api/v1/auth/login/google/callback` que verifica el token doble-submit anti-CSRF (`g_csrf_token` body == cookie), valida el ID token + allow-list (reusa los helpers del flujo JSON), setea la cookie de sesión y redirige a `/leads`. Fallos → `/login?error=google_failed|google_denied` (la página de login muestra el aviso). +4 tests.",
      "Requiere agregar UNA URL en Google Cloud Console → Authorized redirect URIs: `https://inmo-demo.ekoaiautomation.com/api/v1/auth/login/google/callback` (ver docs/setup-google-signin.md). El login por contraseña no cambió.",
    ],
  },
  {
    version: "0.22.0",
    date: "2026-05-29",
    title: "Dashboard móvil tipo app nativa: barra de pestañas inferior + barra superior delgada + notch",
    changes: [
      "Barra de pestañas inferior fija (solo en teléfonos, oculta en escritorio): Discovery · Leads · Inbox · Properties · Stats. La pestaña activa se resalta en violeta según la ruta actual; Inbox muestra un punto ámbar cuando hay pendientes. Es la navegación principal en móvil, estilo app nativa.",
      "La barra superior se simplifica en móvil: marca + idioma + salir (y engranaje de Settings para admins, ya que no está en la tab bar). Los enlaces completos de escritorio se ocultan por debajo de `md`. El escritorio no cambia.",
      "Soporte de notch / safe-area: `viewport-fit=cover` + `theme-color` oscuro + metadatos apple-web-app; la tab bar respeta `env(safe-area-inset-bottom)` y el contenido reserva espacio inferior (vía `body:has(.eko-tabbar)`, sin afectar login/about que no tienen tab bar).",
      "Composer táctil en móvil: selector de canal (SMS/Email/Voz) a ancho completo con áreas de toque más grandes; botones 'Sugerir respuestas' y 'Enviar' más cómodos para el dedo. En escritorio queda igual.",
      "El stacking a una columna ya estaba resuelto en las páginas vía clases responsive de Tailwind; este release añade la capa de chrome nativo móvil que faltaba.",
    ],
  },
  {
    version: "0.21.2",
    date: "2026-05-28",
    title: "Estado 'atendido' del buzón en columna propia (elimina race en Lead.meta)",
    changes: [
      "El estado 'atendido' del buzón se movió de `Lead.meta[\"inbox\"][\"handled_at\"]` (blob JSON) a una columna dedicada `leads.inbox_handled_at` (Alembic 009, con backfill desde el JSON existente). Antes, marcar atendido reasignaba TODO el dict meta → podía pisar (o ser pisado por) otro writer concurrente del meta (p.ej. el enriquecimiento de discovery escribiendo `meta.enrichment`). Ahora son columnas distintas y no se interfieren.",
      "set_handled() ahora hace `lead.inbox_handled_at = when` (sin parseo de ISO ni reasignación de dict). Eliminado el parse silencioso que podía dejar un lead 'pendiente' para siempre ante un valor corrupto.",
      "Test de regresión +1: dos sesiones concurrentes sobre el mismo lead (una escribe meta.enrichment, otra marca atendido) → ambos sobreviven (con el enfoque viejo, el último commit borraba el otro).",
    ],
  },
  {
    version: "0.21.1",
    date: "2026-05-28",
    title: "Fixes de code-review del buzón: visitas pasadas, canal incompatible, counts por canal",
    changes: [
      "Fix: el filtro 'Con cita' mostraba visitas ya pasadas que seguían en estado scheduled/confirmed (nunca se marcaron completed). Ahora _next_visit_per_lead filtra scheduled_at >= ahora → solo cuenta la PRÓXIMA visita futura (antes podía mostrar la más vieja, incluso pasada).",
      "Fix: el selector de canal permitía elegir Email para un lead identificado solo por teléfono (o SMS para uno de email), lo que intentaba enviar a un destinatario inválido y guardaba el mensaje como FAILED. Ahora se valida que el canal pueda alcanzar al identificador del lead (email→dirección, sms/whatsapp→teléfono); si no, devuelve 'channel_identifier_mismatch' sin crear una conversación no entregable, y el composer muestra un aviso claro.",
      "Fix: con ?channel=X los contadores pending/booked se calculaban antes de filtrar por canal → los badges no coincidían con las filas. Ahora se calculan sobre el conjunto ya filtrado por canal.",
      "Tests +4: visita pasada no cuenta como 'con cita' (+ next_visit_at es la futura), canal incompatible rechazado sin crear conversación, create-when-missing usa canal compatible (whatsapp→sms), counts scoped por canal.",
    ],
  },
  {
    version: "0.21.0",
    date: "2026-05-28",
    title: "Bandeja de comunicaciones — buzón de leads con badges, filtros y prioridad",
    changes: [
      "Nueva pestaña 'Bandeja' en el Nav (con contador de pendientes): un buzón estilo correo que lista los leads con conversaciones abiertas. Cada lead muestra su prioridad (🔥/🟡/⚪), un badge del canal pendiente (✉️ Email / 💬 SMS / 🗣️ Voz) cuando esperamos responderle, y 📅 Cita con fecha si tiene una visita agendada; los que no tienen nada pendiente muestran '✅ Al día'.",
      "Filtros: Pendientes (default) / Con cita / Todos. Orden automático por prioridad (score desc; dentro del mismo, el que espera hace más tiempo primero). 'Pendiente' = el último mensaje del lead es entrante y no lo respondimos/atendimos desde entonces.",
      "Marcar 'Atendido' quita el lead de pendientes (se guarda en Lead.meta — sin migración); reaparece solo si entra un nuevo mensaje del lead. Responder desde la conversación también lo saca de pendientes (el último mensaje pasa a saliente). Botón 'Responder' abre la conversación unificada del lead.",
      "Backend: services/inbox.py (estados derivados con queries agrupadas, sin N+1: último mensaje por lead, canales por lead, próxima visita activa) + api/v1/inbox.py (GET /api/v1/inbox?filter=pending|booked|all, GET /inbox/count para el badge del Nav, POST/DELETE /inbox/{id}/handled). Protegido por el mismo require_auth que el resto del data API.",
      "Tests +5: pending refleja el último entrante por canal; 'atendido' suprime y un nuevo entrante re-arma; filter=booked solo con cita ordenado por fecha; orden por prioridad + count coherente; mark-handled idempotente + aislado entre leads + 404.",
    ],
  },
  {
    version: "0.20.0",
    date: "2026-05-28",
    title: "Hilo unificado multicanal por lead + selector de canal + email real (plumbing)",
    changes: [
      "La conversación del lead ahora es UN solo hilo que junta TODOS los canales (SMS + email + WhatsApp) en una línea de tiempo ordenada por fecha; cada burbuja muestra el ícono de su canal y el header lista los canales activos. Antes solo se veía el canal más reciente.",
      "Nuevo endpoint GET /api/v1/conversations/{lead_id}/timeline (mergea los mensajes de todas las conversaciones del lead con su canal; devuelve channels[], primary_channel y resúmenes por canal; 200 vacío si el lead aún no tiene conversación). MessageOut ahora incluye `channel`.",
      "El composer permite ELEGIR el canal al responder (SMS / Email activos; Voz deshabilitada 'próximamente', Phase 13). Si el lead no tenía ese canal, se crea la conversación al enviar. send_human_message acepta `channel` (auto-pick si se omite, back-compat) y rechaza voz; HumanMessageIn.channel = Literal[sms,email,whatsapp] (voz → 422).",
      "Fix: el mensaje enviado ahora aparece al instante (refetch del timeline en el cliente) en vez de depender de router.refresh() — que no re-ejecutaba el efecto del componente cliente (el outbound no se veía hasta recargar).",
      "Email real (plumbing): docker-compose ahora pasa EMAIL_SIMULATED/RESEND_API_KEY/RESEND_FROM/RESEND_WEBHOOK_SECRET al backend (faltaba); RESEND_FROM default movido a un subdominio DEDICADO (realtors.ekoaiautomation.com) — nunca se mezcla con biz.ekoaiautomation.com de Eko AI Main. Nueva guía docs/setup-email.md (alta de subdominio + DNS Cloudflare, aislado de la sales platform).",
      "Tests +8: timeline (merge 2 canales ordenado, tiebreak por id, vacío 200) + selección de canal (reusa conversación existente, crea si falta, voz 422 + unsupported_channel a nivel servicio, auto-pick sin canal).",
    ],
  },
  {
    version: "0.19.0",
    date: "2026-05-27",
    title: "Sign in with Apple — login con Apple (además de Google + contraseña)",
    changes: [
      "Nuevo botón 'Entrar con Apple' en /login, debajo del de Google bajo el mismo separador 'o'. Convive con la contraseña y con Google — ninguno reemplaza al otro.",
      "Usa Sign in with Apple JS en modo popup: Apple autentica en una ventana emergente y devuelve el id_token en la misma página; el frontend lo manda a POST /api/v1/auth/login/apple.",
      "Backend: verify_apple_id_token valida la firma RS256 del identity token contra las llaves públicas de Apple (appleid.apple.com/auth/keys), + iss=https://appleid.apple.com, aud=APPLE_CLIENT_ID (el Services ID) y expiración. Reutiliza la MISMA lista de acceso que Google (resolve_email_access) — la lista se llava por email, no por proveedor — así un correo ya autorizado entra por Apple con el mismo rol.",
      "El flujo popup devuelve el id_token directo, así que NO requiere client secret ni llave .p8: solo el Services ID público. Los correos ocultos de Apple (@privaterelay.appleid.com) solo entran si se autorizan explícitamente.",
      "Config: APPLE_CLIENT_ID (backend) + NEXT_PUBLIC_APPLE_CLIENT_ID + NEXT_PUBLIC_APPLE_REDIRECT_URI (frontend, inlined en build). Pasados por docker-compose + Dockerfile como los de Google. /api/v1/auth/me ahora reporta apple_signin_enabled.",
      "Dependencia nueva: pyjwt[crypto] (PyJWKClient para traer las llaves de Apple + verificación RSA). docs/setup-apple-signin.md con el alta de App ID/Services ID en developer.apple.com + troubleshooting.",
      "Tests +4: verify_apple_id_token (happy path con JWKS+decode mockeados → email verificado; rechaza no-configurado y email no verificado), /me reporta apple_signin_enabled, y los flujos de login Apple (admin fijado + member de DB + denegado fuera de la lista) reutilizando la lista de Google.",
    ],
  },
  {
    version: "0.18.0",
    date: "2026-05-27",
    title: "Botón de versión + historial de cambios en el dashboard",
    changes: [
      "Nuevo botón de versión (pill `v0.18.0`) arriba a la derecha en el Nav, junto al selector de idioma. Al hacer click abre un modal con el historial completo de versiones (versión, fecha, título y cambios) leído de `lib/version.ts` — igual que el de Eko AI Main.",
      "El modal cierra con ESC, click afuera o el botón Cerrar; bloquea el scroll del body mientras está abierto; se renderiza vía portal. Paleta violeta/noir del dashboard e i18n EN/ES.",
    ],
  },
  {
    version: "0.17.0",
    date: "2026-05-27",
    title: "Add Lead — alta manual de leads (demo + uso operativo) con arranque de IA",
    changes: [
      "Nuevo botón 'Add Lead' en /leads + modal para crear un lead a mano. Dos usos con el mismo flujo: (1) el realtor se hace pasar por un cliente para experimentar al agente, y (2) el realtor agrega un lead real (referido/contacto) a su CRM. En ambos casos el lead entra al MISMO pipeline que los capturados automáticamente — scoring, clasificación de intent, matching de propiedades y follow-ups.",
      "Campo opcional 'primer mensaje del cliente': si se llena, se inyecta como mensaje INBOUND y dispara el turno completo de la IA (clasifica + responde + envía por el canal elegido) por el mismo camino que un webhook real. Al guardar, el dashboard cae directo en la conversación del lead con la respuesta de la IA ya generada.",
      "Canales del modal: SMS (default) y Email funcionan hoy; Voz aparece deshabilitada ('próximamente', Phase 13) y WhatsApp queda fuera por ahora (se re-agrega cuando se habilite). El backend solo acepta sms/email para el arranque, así no se crea una conversación que no se pueda entregar.",
      "Backend: POST /api/v1/leads (schema LeadCreate, extra='forbid') con dedupe por identificador (409 si ya existe), marca meta.source='manual' (NO demo → es un lead de primera clase, no borrable por seed_demo --reset) y rescorea al crear. Reutiliza handle_inbound_message para el primer turno; queda detrás del mismo require_auth que el resto del data API.",
      "Frontend: AddLeadButton (modal con paleta violeta/noir del dashboard), leadsApi.create + interface LeadCreate, i18n EN/ES.",
      "Tests +5: create sin mensaje (source=manual + score + sin conversación), create con primer mensaje (LLM mockeado → conversación + inbound/outbound), duplicado 409, falta phone 422, campo desconocido 422.",
    ],
  },
  {
    version: "0.16.2",
    date: "2026-05-27",
    title: "Fix — el login con Google fallaba (faltaba la librería `requests`)",
    changes: [
      "Síntoma: el botón de Google aparecía pero al elegir la cuenta daba 'Google sign-in failed'. Causa: google-auth usa `requests` como transporte HTTP para traer las llaves públicas de Google al validar el ID token, pero `requests` es dependencia OPCIONAL y no estaba en requirements → verify_oauth2_token tiraba 'requests library is not installed' → 401.",
      "Fix: agregado `requests==2.32.3` a backend/requirements.txt. (El password login nunca se vio afectado.)",
      "Test de regresión: `verify_google_id_token` con un token malformado ahora debe fallar con 'invalid_id_token', NO con 'google_auth_library_missing' — así un transporte ausente se detecta en CI (antes los tests mockeaban la verificación y no lo agarraban).",
    ],
  },
  {
    version: "0.16.1",
    date: "2026-05-27",
    title: "Fix — pasar las variables de Google Sign In a los contenedores (compose + Dockerfile)",
    changes: [
      "v0.16.0 trajo el código de Google Sign In pero el docker-compose.yml no pasaba las variables GOOGLE_* al backend, así que GOOGLE_ADMIN_EMAILS no llegaba al contenedor y el admin bootstrap no se sembraba en allowed_users.",
      "Fix: el bloque environment del backend ahora pasa GOOGLE_CLIENT_ID, GOOGLE_ADMIN_EMAILS, GOOGLE_ALLOWED_EMAILS y GOOGLE_ALLOWED_DOMAIN; el frontend recibe NEXT_PUBLIC_GOOGLE_CLIENT_ID como build arg (Next.js inyecta NEXT_PUBLIC_* en tiempo de build, por eso va en el Dockerfile, no en runtime).",
    ],
  },
  {
    version: "0.16.0",
    date: "2026-05-27",
    title: "Google Sign In + control de acceso por admin (equipo gestionado desde Settings)",
    changes: [
      "Login con Google (Google Identity Services): botón 'Entrar con Google' en /login que convive con la contraseña. El backend valida el ID token (firma + email_verified) con la librería google-auth y emite la misma cookie de sesión HMAC.",
      "La sesión ahora lleva identidad + rol (admin/member). El login por contraseña entra como ADMIN (llave maestra); el login por Google toma el rol de la lista de acceso.",
      "La lista de correos permitidos se movió de variables de entorno a la BASE DE DATOS (tabla allowed_users) — el admin la gestiona en vivo desde Settings, sin redeploy. Cada correo tiene rol admin o member.",
      "Settings volvió a la barra de navegación y es SOLO para admins (oculto y 403 para members). Incluye el panel 'Equipo / Acceso': agregar correos Gmail, asignar rol, promover a admin o quitar.",
      "Admin bootstrap fijado por entorno (GOOGLE_ADMIN_EMAILS) — no se puede degradar ni eliminar desde la UI, y la API rechaza quitar al último admin. Junto con la contraseña-admin, esto garantiza que nunca te quedás afuera.",
      "Seguridad: members usan el dashboard pero reciben 403 en /team y /settings; una cuenta de Google fuera de la lista es rechazada con mensaje claro. El flujo GIS no tiene client secret (solo el Client ID público).",
    ],
  },
  {
    version: "0.15.2",
    date: "2026-05-27",
    title: "Nav reordenado: Discovery · Leads · Properties · Analytics · API · EN",
    changes: [
      "Reordené la barra de navegación a: Discovery, Leads, Properties, Analytics, API, EN (selector de idioma). Discovery queda primero (el flujo de prospección arranca ahí).",
      "Settings se quitó de la barra superior para que el menú coincida con lo pedido; la página sigue disponible en /settings.",
    ],
  },
  {
    version: "0.15.1",
    date: "2026-05-27",
    title: "Discovery — fallback a SIMULATED por categoría sin proveedor real (demo siempre muestra leads)",
    changes: [
      "En modo real (DISCOVERY_SIMULATED=false, como corre el demo del ROG) sólo investor_llc traía datos (Colorado SOS gratis); las categorías de vendedor (fsbo/expired/absentee/preforeclosure/high_equity) y renter salían VACÍAS porque no tienen fuente real gratis (ATTOM es pago, FSBO necesita feed licenciado).",
      "Fix: si una categoría no tiene proveedor real configurado (o devuelve vacío), Discovery cae a los leads curados SIMULATED de esa categoría — así las 7 categorías siempre muestran leads demoables. Los datos reales (Colorado SOS, y ATTOM cuando se ponga la key) tienen precedencia cuando existen.",
      "Test: en modo real, fsbo sin proveedor sigue devolviendo leads simulados.",
    ],
  },
  {
    version: "0.15.0",
    date: "2026-05-27",
    title: "Discovery v2 — búsqueda reorientada a leads inmobiliarios reales (no negocios)",
    changes: [
      "Discovery dejó de buscar 'negocios' (Google Maps/Yelp/LinkedIn) y ahora busca LEADS INMOBILIARIOS por categoría, como prospecta un agente. Vendedores: FSBO (venta por dueño), listings expirados, dueños ausentes/fuera del estado, pre-ejecución (distressed), alta plusvalía (likely-to-sell). Compradores: inversores LLC, inquilinos/relocators.",
      "Investigación profunda documentada en docs/discovery-realestate-research.md (fuentes por ROI, APIs accesibles ATTOM/PropStream/county records/Colorado SOS, y cumplimiento TCPA/DNC).",
      "Cada lead trae motivación ('listing expiró hace 2 semanas', 'notice of default'), timeline (inmediato/3-6m/explorando), tipo de propiedad y valor estimado — que el enriquecimiento usa para clasificar intent (vendedor→valuation, comprador→buy/rent) y puntuar el calor del lead.",
      "SIMULATED-first como siempre: set curado de ~17 leads CO realistas por categoría, $0 sin keys. Real por categoría: investor_llc vía Colorado SOS (GRATIS, ya andaba); absentee/preforeclosure/high_equity vía ATTOM (ATTOM_API_KEY, stub key-gated); fsbo/expired/renter requieren feed licenciado (quedan SIMULATED).",
      "API: /discovery/search ahora toma `category` (en vez de `sources`) + `query` opcional de refine. BusinessOut/Lead.meta llevan motivation/timeline/property_type/est_value.",
      "Frontend: chips de categoría (Vendedores / Compradores) en vez de toggles de fuente, refine opcional, y los resultados muestran motivación + timeline + tipo + valor. Aviso de cumplimiento DNC/TCPA visible (los leads son prospectos, no contactos con consentimiento). i18n EN/ES.",
      "Tests actualizados a categorías (search simulado por categoría, filtrado, default a fsbo, cap).",
    ],
  },
  {
    version: "0.14.4",
    date: "2026-05-27",
    title: "Fix — error real visible en la UI (no más 'body stream already read')",
    changes: [
      "El cliente API (`lib/api.ts`) leía el body de una respuesta de error dos veces (`res.json()` y luego `res.text()` en el catch), lo que tiraba 'Failed to execute text on Response: body stream already read' y TAPABA el error real (p.ej. un 500 del backend se mostraba como ese mensaje confuso).",
      "Fix: helper `errorDetail()` que lee el body UNA sola vez como texto y luego intenta `JSON.parse` para sacar el `detail`. Aplicado en `api()` y en `discoveryApi.upload()`.",
      "Contexto: el síntoma apareció cuando el backend devolvió 500 porque el disco del ROG estaba al 100% y Postgres quedó en recovery mode (crash-loop por 'No space left on device'); se liberó espacio (Docker build cache) y la base se recuperó. Este fix asegura que la próxima vez se vea el error real, no el de doble lectura.",
    ],
  },
  {
    version: "0.14.3",
    date: "2026-05-27",
    title: "Discovery — enriquecimiento server-side (deja de depender del navegador)",
    changes: [
      "Problema: leads que pasaban por el flujo pero quedaban sin enriquecer. Causa: el enriquecimiento solo lo disparaba el loop del FRONTEND sobre los leads recién CREADOS — así que leads importados antes de la clasificación (v0.14.2), o saltados por dedupe al re-importar, o si el usuario cerraba la pestaña, nunca se enriquecían (quedaban score 0, sin intent).",
      "Fix: worker server-side de enriquecimiento. `enrich_pending_leads()` busca leads de discovery sin clasificar (score 0) y los enriquece; corre como loop in-process (`ENRICHMENT_ENABLED`, cada 120s) igual que el de follow-ups, + endpoint manual `POST /api/v1/discovery/enrich-pending`. Ahora el enriquecimiento NO depende del navegador: todo lead de discovery termina clasificado aunque la UI no lo haya tocado.",
      "Retry-cap: `enrich_lead` cuenta intentos en `meta.enrichment.attempts`; el sweep abandona un lead tras 3 fallos para no reintentar infinito.",
      "Backfill: al desplegar, el worker (o el endpoint manual) clasifica los leads viejos que estaban en score 0 / sin intent.",
      "El loop del frontend se mantiene como feedback inmediato (barra de progreso); el worker server-side es la red de seguridad. Tests +1 (sweep solo toca discovery sin clasificar, respeta el cap, no toca leads de conversación).",
    ],
  },
  {
    version: "0.14.2",
    date: "2026-05-26",
    title: "Discovery — los leads importados ahora se clasifican (intent + score 🔥) como el resto",
    changes: [
      "Los leads de discovery aparecían 'pelados' en /leads (status new, sin intent, score 0 ⚪) frente a los leads trabajados que muestran 🔥/qualified/buy. Ahora el enriquecimiento TAMBIÉN clasifica y puntúa el lead, así muestra los mismos badges (IntentBadge + ScoreBadge con fueguito).",
      "El LLM de enriquecimiento ahora devuelve también `intent` (buy/rent/valuation/other — best-fit si el contacto pudiera ser cliente, sino other) y `relevance` (0-10). enrich_lead setea `lead.intent` y calcula `lead.score` + `score_breakdown` con un scoring propio para leads prospectados (sin conversación): partner_type (referral_partner 35 / prospect 32 / vendor 18 / competitor 6 / other 12) + relevance×2 + contacto real (+25) + web (+10), mapeado a tier hot≥67/warm≥34/cold con los mismos umbrales que scoring.py.",
      "Resultado: un broker hipotecario que refiere (referral_partner) con contacto y alta relevancia sale 🔥 hot; un competidor sin contacto sale ⚪ cold — y la lista de leads los rankea por score junto a los demás.",
      "El status se mantiene en 'new' (es honesto: son leads recién traídos, sin trabajar). Si el enriquecimiento falla, el lead se guarda igual sin clasificar (no se pierde).",
      "Tests +3: _coerce de intent/relevance (normaliza + clampa), discovery_score (referral+contacto+web+relevancia→hot, other sin nada→cold), y el happy path ahora verifica que enrich setea lead.intent=buy + score>0 + breakdown source=discovery_enrichment.",
    ],
  },
  {
    version: "0.14.1",
    date: "2026-05-26",
    title: "Hotfix — ensanchar leads.phone 32→254 (importar discovery daba 500)",
    changes: [
      "FIX: importar leads de discovery con identificador largo (URLs de LinkedIn, o la clave sintética `discovery:<fuente>:<slug>:<ciudad>`) daba HTTP 500 `StringDataRightTruncationError`. Causa raíz: la columna `leads.phone` seguía siendo VARCHAR(32) en la base, aunque el modelo declara String(254) desde Phase 3 — la migración de Phase 3 nunca llegó a ensanchar la columna (los emails <32 chars funcionaban de casualidad).",
      "Migración Alembic 007_phase12_widen_phone: `ALTER leads.phone TYPE VARCHAR(254)` para alinear la base con el modelo. Operación de ensanchado segura (sin pérdida de datos, mantiene el índice único).",
      "Sin esto, el fix de v0.14.0 (importar leads sin contacto) fallaba en producción para la mayoría de los resultados de Colorado SOS/LinkedIn.",
    ],
  },
  {
    version: "0.14.0",
    date: "2026-05-26",
    title: "Discovery fix — los leads SÍ se guardan + enriquecimiento con barra de progreso",
    changes: [
      "FIX crítico: al darle 'Importar seleccionados' los leads no aparecían en /leads. Causa: el import usaba phone|email como identificador y la mayoría de las fuentes (Colorado SOS, LinkedIn) no traen ni teléfono ni email → se saltaban TODOS silenciosamente. Ahora el identificador cae en cascada phone → email → website → clave sintética estable `discovery:<fuente>:<slug>:<ciudad>`, así cada negocio con nombre se importa Y los re-imports deduplican en vez de duplicar.",
      "El import ahora devuelve `lead_ids` (los IDs creados) para poder enriquecerlos.",
      "NUEVO enriquecimiento de leads (`services/enrichment.py` + `POST /api/v1/discovery/enrich/{lead_id}`): por cada lead importado el LLM (Kimi/MiniMax json_mode) infiere tipo de negocio normalizado, partner_type (referral_partner/vendor/prospect/competitor), un resumen, un ángulo de outreach y tags — guardado en `meta.enrichment`. Marca `contact_missing` cuando no hay teléfono/email real. Graceful: si el LLM falla o devuelve JSON inválido, `status=failed` y nunca se pierde el lead.",
      "Barra de progreso real: tras importar, el frontend enriquece lead por lead mostrando una barra X/N que avanza visiblemente, y al terminar muestra un resumen + link 'Ver en Leads'. Antes no había ninguna señal de procesamiento.",
      "La tabla de /leads ahora muestra los leads de discovery sin contacto de forma limpia (identificador sintético → '—' con icono de lupa; URLs como linkedin.com/in/… con icono de globo) en vez del slug crudo.",
      "Tests +9: lead_identifier (cascada + sintético determinista), import sin contacto AHORA crea + deduplica + devuelve lead_ids, _coerce (partner_type inválido→other, tags string→list + cap 4), enrich_lead (happy path persiste meta + contact_missing, graceful ante LLM caído y JSON inválido).",
    ],
  },
  {
    version: "0.13.0",
    date: "2026-05-26",
    title: "Phase 12 — Discovery: búsqueda de leads (4 fuentes) + importar desde cualquier archivo",
    changes: [
      "Nueva pestaña Discovery (como la del sales platform): buscá nuevos leads de negocios en 4 fuentes — Google Maps, Yelp, LinkedIn y Colorado SOS — y sumá una sección para importar tu base de datos existente desde CUALQUIER archivo (PDF, JPG/PNG, TXT, CSV, XLSX, HTML).",
      "Flujo preview-and-select: buscar/subir devuelve resultados transitorios (no se persisten); el dashboard muestra un checklist con select-all y vos elegís cuáles importar → se crean como Leads (status new, meta.source). Dedupe por identificador (teléfono, sino email) contra leads existentes.",
      "services/discovery.py (portado y adaptado del sales platform Eko AI Main, drop de Paperclip): patrón SIMULATED-first como listings.py. Default DISCOVERY_SIMULATED=true → set curado de negocios CO reales-plausibles (sin keys). Adapters reales por fuente: Colorado SOS (Socrata público, GRATIS sin key), Yelp Fusion, Google Maps (Outscraper), LinkedIn (SerpApi) — cada uno degrada a [] sin su key.",
      "services/file_import.py — extracción 'cualquier formato': PDF (pypdf), XLSX (openpyxl), imágenes JPG/PNG vía OCR (pytesseract + tesseract-ocr en el Dockerfile), CSV/TXT/HTML (stdlib + strip de tags). Luego extract_leads pasa el texto por el LLM (json_mode) para sacar contactos como array JSON, con degradación graceful (output malo → [], nunca crashea).",
      "API protegida bajo /api/v1/discovery: POST /search (query/city/state/sources/max_results), POST /upload (multipart, cap FILE_IMPORT_MAX_MB=25), POST /import (crea los leads elegidos). Frontend: /discovery (DiscoveryPanel con 4 chips de fuente + ResultsList reutilizable + FileImport con drag-drop). Link Discovery en el Nav (icono Search).",
      "config + .env.example + compose: DISCOVERY_SIMULATED + YELP_API_KEY/OUTSCRAPER_API_KEY/SERPAPI_API_KEY (se reusan las keys del sales platform) + FILE_IMPORT_MAX_MB. requirements: pypdf/openpyxl/pillow/pytesseract. docs/setup-discovery.md (qué fuente necesita qué key; Colorado SOS gratis; flip DISCOVERY_SIMULATED=false).",
      "Tests +13 (total 145): test_discovery.py (6 — búsqueda simulada devuelve negocios, filtro por fuente, cap max_results, sanitize_email, import crea+dedupe, import sin identificador skip) + test_file_import.py (7 — extract_text plaintext/csv/html-strip/empty, extract_leads parsea JSON array, tolera prosa, output malo→[], texto vacío no llama LLM).",
      "Voz (VAPI/Retell) renumerado a Phase 13.",
    ],
  },
  {
    version: "0.12.0",
    date: "2026-05-26",
    title: "Phase 11 — Hardening para 1er cliente: auth del dashboard + analíticas",
    changes: [
      "Login del dashboard (una oficina = un password compartido): página /login + AuthGuard que redirige si la sesión falta. Token de sesión firmado con HMAC (cookie httpOnly, sin dependencia nueva). Botón de salir en el Nav.",
      "Gate por `AUTH_ENABLED`: el data API (leads/conversations/visits/settings/properties/analytics) requiere login cuando está activo; webhooks + health quedan abiertos. Default OFF (dev + demo público abiertos); el instalador lo activa con un password. WARN al startup si APP_ENV=production y AUTH_ENABLED=false.",
      "Página /analytics: funnel por status, tasa de conversión, leads por canal, por tier de score (🔥/🟡/⚪), tiempo de primera respuesta promedio, y nuevos leads por día (14d). Endpoint GET /api/v1/analytics (solo lectura). Sin librería de charts (barras div).",
      "config + .env.example + compose: AUTH_ENABLED/DASHBOARD_PASSWORD/AUTH_SECRET/AUTH_TTL_HOURS. El instalador (scripts/install.sh) pregunta el password del dashboard y activa auth + genera AUTH_SECRET.",
      "i18n EN/ES para login + analytics; link Analytics en el Nav.",
      "Tests +6 (total 132): auth service (password/token/tamper/expiry) + gate (abierto si disabled, 401/login/cookie si enabled) + envelope de analytics.",
      "Voz (VAPI/Retell) renumerado a Phase 12.",
    ],
  },
  {
    version: "0.11.0",
    date: "2026-05-26",
    title: "Phase 10 — Nurture autónomo + el agente ofrece listings en la conversación",
    changes: [
      "Seguimiento autónomo post-visita: al agendar una visita se encola un recordatorio 24h antes + secuencia post-visita (24h '¿qué te pareció?', 72h nudge si no respondió, 7d 'nuevas similares'). Mensajes bilingües enviados como el agente IA por el canal del lead.",
      "Modelo FollowUp + Alembic 006 (lead/visit/kind/status/scheduled_for, UNIQUE visit+kind → enqueue idempotente). services/followups.py: enqueue_for_visit + process_due_followups (se salta si human_takeover, visita cancelada, o el 72h si el lead ya respondió tras la visita).",
      "Worker in-process (loop asyncio en main.py, FOLLOWUPS_ENABLED + FOLLOWUPS_INTERVAL_SECONDS) que procesa los vencidos; scripts/run_followups.py para cron. El booking de visita encola la secuencia.",
      "El agente ahora OFRECE listings en la conversación: si el lead es buy/rent y tiene zona, el orquestador inyecta los listings emparejados REALES en el system prompt (solo esos, sin inventar) y el LLM los ofrece naturalmente. Cierra el loop de Phase 7 (antes el matching era solo dashboard).",
      "Fix: el matcher coercía mal el presupuesto (float del classifier * Decimal → crash silencioso); normalizado con Decimal(str()). Sin esto la inyección fallaba en vivo.",
      "Tests +6 (total 126): followups (enqueue secuencia + idempotente, past-visit sin reminder, envía vencido, human_takeover skip, cancelada no encola) + agente recibe listings reales en el system prompt.",
      "Voz (VAPI/Retell) renumerado a Phase 11.",
    ],
  },
  {
    version: "0.10.0",
    date: "2026-05-26",
    title: "Dashboard multilingüe (EN default + ES) con selector de idioma",
    changes: [
      "El dashboard ahora es multilingüe: inglés por defecto, español como segunda opción, con un selector de idioma (globo + EN/ES) en el Nav, visible en TODAS las páginas.",
      "lib/i18n.tsx: LanguageProvider client + hook useI18n + diccionarios completos EN/ES. La elección persiste en localStorage y sincroniza <html lang>. t(key) con fallback a EN y a la propia key.",
      "Todos los strings de UI pasan por t(): Nav, páginas (leads/propiedades/settings/detalle), badges (status/intent/score/visit), tabla y detalle de leads, composer, sugerencias, matches, visitas, booking, propiedades, settings, takeover, mensajes.",
      "Formatters locale-aware: relativeTime/exactTime/formatBudget (USD, en/es) + fechas de visitas/booking según el idioma activo.",
      "PageHeader client para los títulos; la página de detalle de lead es client. Landing /about con copy refrescado (MLS matching).",
      "Default English alineado con el pivote USA; el agente backend ya respondía en el idioma del lead (Phase 3) — esto hace bilingüe también la interfaz del realtor.",
    ],
  },
  {
    version: "0.9.1",
    date: "2026-05-26",
    title: "SMS hardening — A2P MessagingServiceSid + delivery status callbacks",
    changes: [
      "Tras leer la doc oficial de Twilio, dos mejoras de producción del canal SMS: (1) envío vía MessagingServiceSid para A2P 10DLC, (2) tracking de entrega real vía StatusCallback.",
      "send_sms: si TWILIO_MESSAGING_SERVICE_SID está seteado, envía con MessagingServiceSid (usa la campaña/pool A2P registrado) en vez del From crudo — recomendado por Twilio para entrega US. Fallback a TWILIO_PHONE_NUMBER.",
      "StatusCallback: nuevo endpoint POST /api/v1/webhooks/sms/status. Si TWILIO_STATUS_CALLBACK_URL está seteado, send_sms pide a Twilio que postee actualizaciones (sent→delivered/undelivered/failed + ErrorCode). El backend refleja el estado final en el Message → el dashboard muestra entrega real (y loguea errores de carrier como 30034 = A2P sin registrar). Mapper twilio_status_to_delivery.",
      "config.py + .env.example + compose: TWILIO_MESSAGING_SERVICE_SID + TWILIO_STATUS_CALLBACK_URL.",
      "docs/setup-twilio.md ampliado: registro A2P 10DLC (Sole Proprietor vs Standard), gotcha del webhook del Messaging Service (anula el del número), y opt-out STOP/HELP (Twilio lo maneja por default).",
      "Webhook inbound: log de fallo de firma más limpio (sin el diagnóstico verbose temporal).",
      "Tests +4 (total 120): mapper de estado (1) + status callback e2e (delivered, undelivered/30034→failed, sid desconocido = no-op).",
    ],
  },
  {
    version: "0.9.0",
    date: "2026-05-26",
    title: "Phase 9 — Canal SMS (Twilio)",
    changes: [
      "Tercer canal: SMS vía Twilio Programmable Messaging, sobre la misma arquitectura multicanal de Phase 3 (ParsedMessage + dispatcher + channel='sms'). El agente captura, clasifica, scorea y responde igual que WhatsApp/Email.",
      "services/sms.py: send_sms (SIMULATED loguea / real POST a la REST API de Twilio con basic auth), verify_twilio_signature (HMAC-SHA1 sobre URL + params POST ordenados, keyed por el auth token), parse_inbound_sms(form)->ParsedMessage.",
      "Webhook POST /api/v1/webhooks/sms: parsea el form de Twilio, valida X-Twilio-Signature (salvo SIMULATED), delega al orquestador, responde TwiML vacío (la respuesta sale async vía REST). La URL para la firma es TWILIO_WEBHOOK_URL o se reconstruye de los forwarded headers (proxy/tunnel).",
      "Idempotencia vía UNIQUE messages.external_id (MessageSid) — los reintentos de Twilio no duplican.",
      "config.py + .env.example + compose: SMS_SIMULATED (default true), TWILIO_ACCOUNT_SID/AUTH_TOKEN/PHONE_NUMBER/WEBHOOK_URL. scripts/simulate_inbound_sms.py para smoke testing.",
      "docs/setup-twilio.md: cuenta + número + webhook + firma + notas de costo/seguridad.",
      "Tests +9 (total 116): test_sms_service.py (7 — firma válida/tampered/wrong-token/missing, parse ok/missing, send simulated) + test_sms_webhook_e2e.py (2 — inbound crea lead+conversation channel=sms, idempotencia en reintento).",
      "Voz (VAPI/Retell) sigue diferida como Phase 10 hasta tener cuenta de proveedor.",
    ],
  },
  {
    version: "0.8.0",
    date: "2026-05-26",
    title: "Phase 8 — Lead intelligence (scoring + priorización + digest)",
    changes: [
      "Lead scoring 0-100 determinista y explicable: services/scoring.py puntúa señales que el pipeline ya produjo (intent LLM + entidades extraídas + engagement + recency + visita) SIN llamadas LLM extra por lead, así la lista rankea rápido y barato. Componentes: intent 20 · budget 15 · engagement 15 · urgency 12 · zone 10 · recency 10 · visit 10 · property_type 8. Status gate: WON/LOST→0, PAUSED→mitad.",
      "Columnas leads.score (Int indexado) + score_breakdown (JSON con desglose por componente + tier). Alembic 005. El orquestador recomputa el score tras cada turno inbound; POST /leads/rescore-all para backfill.",
      "Tiers 🔥 hot (≥67) / 🟡 warm (≥34) / ⚪ cold. ScoreBadge en cada fila de la tabla de leads; la lista ahora ordena por score por defecto (sort=score|recent).",
      "GET /leads/digest — top leads calientes/activos (excluye won/lost/paused, score>0) → panel 'Leads calientes — a quién llamar primero' arriba de /leads. scripts/daily_digest.py para cron (imprime el digest, pipe-able a email/Telegram).",
      "Lead detail muestra el ScoreBadge con label en el header. score + score_breakdown expuestos en LeadOut.",
      "Tests +11 (total 107): test_scoring.py (8 — lead vacío 0, fully-qualified=100 hot, won/lost zeroed, paused halved, engagement escala, recency decae, clamp 0-100, umbrales de tier) + test_lead_digest.py (3 — rescore+digest rankea y excluye cerrados, list default sort=score, LeadOut tiene score).",
      "Sin cuentas externas. SMS (Twilio) renumerado a Phase 9, Voz (VAPI/Retell) a Phase 10 — siguen diferidas hasta tener cuentas.",
    ],
  },
  {
    version: "0.7.0",
    date: "2026-05-25",
    title: "Phase 7 — MLS/IDX listings (RESO) + per-lead property matching",
    changes: [
      "Property model reworked para USA: source enum reso/idx/mls/manual + status enum (active/pending/sold/off_market), bedrooms/bathrooms (half-baths 2.5)/sqft/property_type/address/city/state/zip/zone/lat-lng/photos/description/listed_at. Alembic 004 dropea+recrea la tabla placeholder EU (estaba vacía).",
      "services/listings.py: fetch_listings (SIMULATED = set curado de 9 listings Miami / real = RESO Web API OData con RESO_BASE_URL+RESO_ACCESS_TOKEN), sync_listings (upsert idempotente por source+external_id), match_properties_for_lead (gate de intención rent/sale + zona + presupuesto ±10% + tipo).",
      "Endpoints: GET /properties (filtros status/source/city/zone/type/min-max price + paginado), POST /properties/sync (ingest), GET /properties/{id}, GET /leads/{id}/matches (listings que encajan con el lead).",
      "Frontend: página /properties con grid de PropertyCard + filtros zona/precio + botón 'Sincronizar MLS'. MatchesSection en el detalle del lead muestra 'Propiedades sugeridas' con botón 'Enviar al lead' (manda blurb formateado vía composer). Link 'Propiedades' en el Nav.",
      "Listings SIMULATED por default (LISTINGS_SIMULATED=true) — el dashboard + matching funcionan sin cuenta MLS; producción vía docs/setup-mls.md. Las zonas del set demo coinciden con los leads demo (Brickell/Coral Gables/Doral/Wynwood/Edgewater/Little Havana).",
      "scripts/sync_listings.py ingest CLI (idempotente, cron-friendly). config.py + .env.example + docker-compose env (LISTINGS_SIMULATED/PROVIDER/RESO_*).",
      "Tests +12 (total 96): test_listings_service.py (5 — fetch simulado, sale+rent, filtro ciudad, ciudad inexistente vacía, limit) + test_properties_api.py (7 — sync idempotente, list+filtros, filtro precio, get 404, matches 404, buy-lead Brickell sale-only, rent-lead solo rentals).",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-05-25",
    title: "Phase 6 — Single-customer installer + branding panel + public demo",
    changes: [
      "Settings API: GET/PUT /api/v1/settings sobre el singleton AgentSettings (auto-creado con defaults). PUT hace partial update con normalización/dedupe de languages (lowercase, sin vacíos). Cada oficina puede brandear su propia instancia.",
      "Frontend /settings — panel de branding: nombre + teléfono de la agencia, persona del agente (system prompt), saludo, idiomas (chips es/en/pt/fr), horario de atención (por día, open/close o cerrado). Link 'Configuración' en el Nav. Cambios aplican de inmediato a las respuestas.",
      "scripts/install.sh — instalador single-customer interactivo: chequea prereqs (docker/compose/daemon), genera .env con secretos aleatorios fuertes (POSTGRES_PASSWORD, WHATSAPP_VERIFY_TOKEN) mode 600 nunca impresos, build+up, espera health, alembic upgrade head, fija branding vía API. Canales quedan SIMULATED salvo opt-in explícito. --no-prompt para provisioning.",
      "backend/scripts/seed_demo.py — dataset demo idempotente (Sunset Realty Group, Miami): 6 leads bilingües EN/ES + conversaciones realistas + 2 visitas (scheduled/completed). Marca meta.demo=true; --reset borra solo filas demo; --keep-settings preserva branding. Para que inmo-demo.ekoaiautomation.com luzca vivo.",
      "deploy/cloudflared/config.example.yml + docs/setup-demo.md — tunnel DEDICADO para inmo-demo.ekoaiautomation.com (aislado del tunnel eko-landing de la sales platform). Modelo de seguridad: todos los canales SIMULATED (un visitante nunca dispara un envío real), datos seed (sin PII real), opcional Cloudflare Access.",
      "docs/install.md — guía completa de instalación single-office + enable de canales (WhatsApp/Resend/Cal.com) + upgrade. Sin GPU (LLM en la nube Kimi+MiniMax).",
      "CI verde por primera vez desde Phase 1: backend agrega servicio Postgres + alembic upgrade head (los tests con DB ahora corren de verdad) + ruff config ignora 3 reglas que chocan con idioms intencionales (B008 FastAPI Depends, UP042 str-Enum, UP037 SQLAlchemy forward-refs) + auto-fix del resto. Frontend quita cache npm (no había package-lock.json → abortaba el job).",
      "Tests +7 (total 84): test_settings_api.py (GET auto-create defaults, PUT update + persiste, partial update no toca otros campos, languages normalize/dedupe, body vacío 400, campo desconocido 422, languages vacío 422). test_models singleton hecho robusto (no acopla agency_name a un valor fijo).",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-05-25",
    title: "Phase 5 — Calendar booking (Cal.com) con SIMULATED + dashboard VisitsSection",
    changes: [
      "Visit model (id, lead_id FK CASCADE, calendar_provider, external_booking_id UNIQUE, status enum scheduled/confirmed/cancelled/completed/no_show, scheduled_at indexed, duration_minutes, timezone, property_address, meeting_url, notes, timestamps). Alembic migration 003_phase5_visits.",
      "services/calendar_cal.py — Cal.com v2 API wrapper: list_available_slots, create_booking, cancel_booking. SIMULATED mode genera slots weekday 10/11/14/15/16 in-memory + IDs calcom-sim-<uuid>; producción hace HTTP a api.cal.com con cal-api-version 2024-08-13 header.",
      "4 endpoints nuevos: GET /leads/{id}/calendar/slots?days=N&timezone=, POST /leads/{id}/calendar/book, GET /leads/{id}/visits, POST /visits/{id}/cancel. Slots filtra busy_starts del lead (no double-booking en la misma conversación).",
      "Auto-pick email vs phone para attendee: si lead.phone contiene '@' → email para Cal.com; sino phone. Lead sin email + producción real → 503 con mensaje claro.",
      "Frontend: VisitsSection en LeadDetail muestra upcoming + past visits con cards (VisitStatusBadge, fecha localizada ES, dirección, notas, cancel button). BookingDialog modal con date-grouped slot picker, dirección opcional, notas, confirm.",
      "Dashboard URLs: /leads/{id} ahora muestra (top→bottom): Header con metadata + TakeoverToggle (Phase 2), Conversación chat (Phase 1-3), Composer + Sugerir (Phase 4), VisitsSection + Agendar visita (Phase 5).",
      "Tests +13 (total 77): test_calendar_service.py (7 — weekday-only, hours match, busy filter, simulated mode, booking sim id, cancel sim, calcom-sim-* always-local-cancel) + test_visits_api.py (6 — slots endpoint, slots 404, book creates Visit, list visits, cancel flips + rejects re-cancel, no double-booking).",
      "docs/setup-calcom.md producción walkthrough (Cal.com account + event type + API key + DNS-less). CALENDAR_SIMULATED env var (default true) + CALCOM_BASE_URL (default api.cal.com).",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-05-25",
    title: "Phase 4 — Composer manual + AI reply suggestions (completa el loop de takeover)",
    changes: [
      "Composer box en /leads/[id]: el realtor escribe una respuesta y la envía vía el canal del lead (WhatsApp/Email). Se persiste como Message(sender=HUMAN, direction=OUTBOUND) y se rutea por el dispatcher multichannel existente.",
      "Botón 'Sugerir respuestas': genera 3 borradores de respuesta vía LLM (Kimi/MiniMax). Cada sugerencia es clickeable y llena el textarea del composer — el realtor puede editarla antes de enviar.",
      "Backend nuevo: POST /api/v1/leads/{id}/messages (human send con auto-pick del canal de la última conversación activa; threading email via In-Reply-To del último inbound) + POST /api/v1/leads/{id}/suggestions (genera N respuestas en formato JSON array, degrada a [] + error en caso de LLM fail o JSON inválido).",
      "Orchestrator: 2 funciones nuevas — send_human_message + generate_reply_suggestions. Usan el dispatcher existente, la detección de idioma del Phase 3, y AgentSettings.languages.",
      "Auto-pick canal: si el lead tiene múltiples conversaciones activas (multichannel), el composer usa la última activa. Para email auto-prepende 'Re:' + In-Reply-To header.",
      "UX: 'count' clampado a [1, 5]. Composer muestra contador 0/4000 chars. Errores in-line (no toast/modal). router.refresh() tras send → nueva burbuja aparece en el chat sin recargar.",
      "Tests +8: human-send happy path (WhatsApp simulated routing), lead-not-found error, empty text 400, lead-without-conversation error, suggestions happy path, suggestions con prose alrededor del JSON, suggestions LLM fail degrade graceful, suggestions count clamp 99→5.",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-05-25",
    title: "Phase 3 — Multichannel + Email (Resend) + Bilingual (USA pivot)",
    changes: [
      "Pivote estratégico USA: el target de clientes pasa de inmobiliarias EU (WhatsApp-first) a realtors USA donde dominan SMS, Email y llamadas. WhatsApp queda como canal opcional para clientes internacionales.",
      "Multichannel refactor: schema agnóstico al canal. Renames messages.wa_message_id→external_id, wa_status→delivery_status, conversations.wa_thread_id→external_thread_id. + messages.subject (email). leads.phone widened 32→254 chars (acepta emails como identifier). Alembic migration 002_phase3_multichannel preserva rows existentes.",
      "ParsedMessage común en services/_common.py — dataclass con channel, external_id, from_identifier, content, subject, thread_id. Cada canal (WhatsApp / Email / SMS / Voice) emite el mismo tipo.",
      "Orchestrator con dispatcher: handle_inbound_message ahora rutea outbound a whatsapp_send / email_send según conversation.channel. Lazy imports — un deploy puede no tener Resend SDK si no usa email.",
      "Email channel (Resend): services/email.py con send_email (threading via In-Reply-To + References), parse_inbound_email (Resend payload + HTML fallback), verify_resend_signature (Svix-style HMAC con multi-sig support). EMAIL_SIMULATED=true en dev (loguea outbound, no requiere cuenta Resend ni DNS).",
      "Webhook nuevo: POST /api/v1/webhooks/email — mismo contrato que WhatsApp (200 + UNIQUE external_id catches retries).",
      "Bilingüe: services/i18n.py con detect_language (langdetect, seed determinista) + pick_supported_language (whitelist AgentSettings.languages) + language_instruction (steering line ES/EN para el system prompt). Detecta del último inbound, NO bias en réplicas históricas del agente. Classifier acepta language_hint opcional.",
      "Dashboard: MessageBubble muestra channel icon (envelope email, message-circle WhatsApp, message-square SMS, phone voice) + asunto del email visible cuando applies. LeadsTable muestra heuristic-based glyph al lado del identificador (email vs phone).",
      "Backend: PATCH lead endpoint Phase 2 sigue funcionando. Pydantic schemas en conversations.py actualizados al naming nuevo (external_id / delivery_status / subject / external_thread_id).",
      "Tests: 55 total (45 + 10 nuevos = 8 email service + 9 i18n - 7 duplicados/colectados). E2E email crea Lead via address, Conversation(channel=email), 2 Messages con subject + threading.",
      "Frontend lib/api.ts: Message + Conversation interfaces alineadas al backend nuevo (external_id, delivery_status, subject, external_thread_id).",
      "Roadmap reordenado post-pivote USA: Phase 4=SMS (Twilio), Phase 5=Voice (VAPI/Retell), Phase 6=Calendar (movido desde Phase 3), Phase 7=MLS/IDX (USA equivalente Idealista), Phase 8=installer + demo subdomain.",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-05-25",
    title: "Phase 2 — Realtor dashboard (lista leads + chat view + human takeover)",
    changes: [
      "Dashboard frontend funcional en Next.js 14 App Router. Reemplaza el landing placeholder en `/` (que ahora redirige a `/leads`). La landing vieja queda accesible en `/about`.",
      "`/leads` — tabla de leads con filtros por status (Nuevo/Cualificado/Visitando/Post-visita/Cerrado/Perdido/Pausado) e intent (Alquiler/Compra/Tasación/Otro). Click en un lead → vista detalle.",
      "`/leads/[id]` — vista detalle con metadata del lead (nombre, teléfono, zona, presupuesto, tipo, urgencia, timestamps) + conversación completa estilo chat (burbujas inbound/outbound, indicador de provider LLM, status de envío Meta) + toggle de control humano.",
      "Toggle 'Humano vs IA' — botón que llama `PATCH /api/v1/leads/{id}` con `{human_takeover: true|false}`. Cuando está ON, el orchestrator NO genera respuesta automática para el siguiente mensaje entrante (Phase 1 ya respeta esta flag).",
      "Componentes: `Nav` (top bar con branding + links), `StatusBadge` + `IntentBadge` (paleta por categoría), `FilterBar` (querystring-based, Suspense para SSR), `LeadsTable` (lista con virtualización ligera), `MessageBubble` (chat-style con sender icons), `LeadDetail`, `TakeoverToggle`.",
      "API client tipado en `lib/api.ts` — interfaces TypeScript para Lead, Conversation, Message + funciones `leadsApi.list/get/patch` y `conversationsApi.get`. Helper `format.ts` con tiempos relativos en castellano + formato de presupuesto.",
      "Backend: nuevo endpoint `PATCH /api/v1/leads/{id}` con schema `LeadPatch` (partial update, `extra='forbid'` rechaza campos desconocidos con 422). Acepta name, status, intent, zone, budget_min/max, property_type, urgency, human_takeover.",
      "`next.config.js` proxya `/api/*` a `INTERNAL_API_URL` (default `http://backend:8000`) — cliente JS siempre habla same-origin, funciona desde LAN/Tailscale/futuro Cloudflare sin reconfigurar URLs.",
      "Tests +8: `test_leads_api.py` cubre list envelope, get 404, PATCH takeover toggle, PATCH partial update (status+zone sin tocar name), PATCH body vacío 400, PATCH campo desconocido 422, PATCH status inválido 422, PATCH 404. Total ahora: 33 tests.",
      "Brand rename completo Inmobiliario → Realtors en `<title>`, landing copy, README.",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-05-25",
    title: "Phase 1 CORE — WhatsApp 24/7 agent with Kimi + MiniMax fallback",
    changes: [
      "Identity setup: CLAUDE.md raíz con anti-patterns + port map + 3-líneas-de-trabajo distinction; GitHub topics + 5 milestones; CI workflow (ruff + pytest + tsc + lint).",
      "Port remap: container stack `eko-realestate-*` en 3004/8011/5434/6381 para coexistir con la sales platform prod (3001/8000/5432/6379), su main dev paralela (3003/8010/5433/6380) y el preview pricing-v2 (3002). Cero colisión.",
      "DB layer: SQLAlchemy 2.x async + Alembic baseline migration. 5 modelos: Lead (con status/intent enums, budget, zone, urgency, human_takeover), Conversation, Message (UNIQUE wa_message_id para idempotencia de webhooks), Property (placeholder Phase 4), AgentSettings (singleton con persona en castellano + business_hours).",
      "LLM client: Kimi 2.6 primary + MiniMax M2.7 fallback. Fallback INLINE por request (si Kimi timeout/429/5xx, mismo request reintenta con MiniMax antes de fallar). Ambos via SDK `anthropic` con `base_url` distinto. A/B test script con 5 prompts ES típicos validó calidad real (Kimi ~3.4s avg, MiniMax ~5.6s; ambos producen castellano natural).",
      "Intent classifier: clasifica rent/buy/valuation/other + extrae zona, presupuesto, tipo, urgencia. Pydantic schema valida; degrada a OTHER + log raw_response cuando JSON inválido. Coerce \"1.500€\" → 1500.0.",
      "WhatsApp webhook: GET handshake verify (token + challenge), POST inbound con HMAC-SHA256 verify (`X-Hub-Signature-256`). Modo SIMULATED por default (loguea outbound en vez de POST a Meta) — desarrollo sin Meta Business App. Warning al startup si SIMULATED=true Y APP_ENV=production.",
      "Conversation orchestrator: inbound → upsert Lead → save inbound Message → classify intent (aplica si confidence ≥ 0.55) → genera reply con LLM → save outbound Message (status=PENDING) → send via WhatsApp Cloud API → update wa_message_id + status (SENT/FAILED). Idempotencia via UNIQUE wa_message_id (Meta retries no duplican leads).",
      "API routes: `GET /api/v1/leads` (lista paginada con filtros status/intent), `GET /api/v1/leads/{id}` (detail), `GET /api/v1/conversations/{lead_id}` (full history).",
      "Tests: 23 total — 4 LLM fallback (mocked anthropic SDK), 7 classifier (mocked LLM responses), 7 signature (HMAC valid/invalid/missing/tampered/wrong-secret), 2 webhook E2E (full flow + idempotency), 2 models (roundtrip + AgentSettings), 1 health. Live DB required for E2E + models.",
      "Script `simulate_inbound.py` para CLI testing manual: `python scripts/simulate_inbound.py \"+34666123456\" \"Hola...\"` → POST simulado al webhook.",
      "Doc `setup-whatsapp.md` con flow completo Meta App → secrets → webhook registration → production checklist + troubleshooting.",
    ],
  },
  {
    version: "0.0.1",
    date: "2026-05-25",
    title: "Bootstrap",
    changes: [
      "Repo skeleton: FastAPI backend + Next.js frontend + Postgres + Redis + Ollama via docker-compose.",
      "Health endpoint at GET /api/v1/health.",
      "Landing placeholder with brand-aligned design (Eko AI violet palette).",
      "README + roadmap + architecture docs.",
    ],
  },
];
